// Generated by swift-winrt
// swiftlint:disable all

import WinUI

public typealias Brush = MicrosoftUIXamlMedia_Brush
public typealias CacheMode = MicrosoftUIXamlMedia_CacheMode
public typealias ElementCompositeMode = MicrosoftUIXamlMedia_ElementCompositeMode
public typealias FontFamily = MicrosoftUIXamlMedia_FontFamily
public typealias GeneralTransform = MicrosoftUIXamlMedia_GeneralTransform
public typealias Geometry = MicrosoftUIXamlMedia_Geometry
public typealias ImageSource = MicrosoftUIXamlMedia_ImageSource
public typealias Projection = MicrosoftUIXamlMedia_Projection
public typealias RectangleGeometry = MicrosoftUIXamlMedia_RectangleGeometry
public typealias Shadow = MicrosoftUIXamlMedia_Shadow
public typealias SolidColorBrush = MicrosoftUIXamlMedia_SolidColorBrush
public typealias SystemBackdrop = MicrosoftUIXamlMedia_SystemBackdrop
public typealias Transform = MicrosoftUIXamlMedia_Transform
public typealias XamlLight = MicrosoftUIXamlMedia_XamlLight