// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Represents a sequential stream of bytes to be read.
public typealias WindowsStorageStreams_IInputStream = any WindowsStorageStreams_IInputStreamProtocol


/// Represents a sequential stream of bytes to be read.
public protocol WindowsStorageStreams_IInputStreamProtocol: WindowsFoundation_IClosableProtocol {
    /// Reads data from the stream asynchronously.
    /// - Parameter buffer: A buffer that may be used to return the bytes that are read. The return value contains the buffer that holds the results.
    /// - Parameter count: The number of bytes to read that is less than or equal to the Capacity value.
    /// - Parameter options: Specifies the type of the asynchronous read operation.
    /// - Returns: The asynchronous operation.
    func readAsync(_ buffer: WindowsStorageStreams_IBuffer?, _ count: Swift.UInt32, _ options: WindowsStorageStreams_InputStreamOptions) throws -> WindowsFoundation_IAsyncOperationWithProgress<WindowsStorageStreams_IBuffer?, Swift.UInt32>
}