// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Paints an area with a solid color. The solid color is defined by a Color value.
public final class MicrosoftUIXamlMedia_SolidColorBrush: MicrosoftUIXamlMedia_Brush, @unchecked Sendable {
    /// Initializes a new instance of the SolidColorBrush class with no color.
    public override init() throws {
        let _instance = COM.COMReference(transferringRef: try Self._iactivationFactory.activateInstance(binding: MicrosoftUIXamlMedia_SolidColorBrushBinding.self))
        super.init(_wrapping: _instance.cast()) // Transitively casts down to IInspectable
    }

    /// Initializes a new instance of the SolidColorBrush class with the specified Color.
    /// - Parameter color: The color to apply to the brush.
    public init(_ color: WindowsUI_Color) throws {
        let _instance = try Self._isolidColorBrushFactory.createInstanceWithColor(color)
        super.init(_wrapping: _instance.cast()) // Transitively casts down to IInspectable
    }

    /// The brush's color. The default value is Transparent.
    public var color: WindowsUI_Color {
        get throws {
            try _isolidColorBrush.get_Color()
        }
    }

    /// Sets the color of this SolidColorBrush.
    /// - Parameter newValue: The brush's color. The default value is Transparent.
    public func color(_ value: WindowsUI_Color) throws {
        try _isolidColorBrush.put_Color(value)
    }

    /// Gets or sets the color of this SolidColorBrush.
    public var color_: WindowsUI_Color {
        get {
            try! self.color
        }
        set {
            try! self.color(newValue)
        }
    }

    /// The identifier for the Color dependency property.
    public static var colorProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_isolidColorBrushStatics.get_ColorProperty())
        }
    }

    /// Identifies the Color dependency property.
    public static var colorProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.colorProperty)
    }

    // MARK: Implementation details

    public init(_wrapping inner: consuming COM.COMReference<SWRT_MicrosoftUIXamlMedia_ISolidColorBrush>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    private var _lazyISolidColorBrush: COM.COMReference<SWRT_MicrosoftUIXamlMedia_ISolidColorBrush>.Optional = .none

    internal var _isolidColorBrush: COM.COMInterop<SWRT_MicrosoftUIXamlMedia_ISolidColorBrush> {
        get throws {
            try _lazyISolidColorBrush.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_MicrosoftUIXamlMedia_ISolidColorBrush.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Microsoft.UI.Xaml.Media.SolidColorBrush")
            }
        }
    }

    private static var _lazyISolidColorBrushFactory: COM.COMReference<SWRT_MicrosoftUIXamlMedia_ISolidColorBrushFactory>.Optional = .none

    internal static var _isolidColorBrushFactory: COM.COMInterop<SWRT_MicrosoftUIXamlMedia_ISolidColorBrushFactory> {
        get throws {
            try _lazyISolidColorBrushFactory.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_MicrosoftUIXamlMedia_ISolidColorBrushFactory.self)).cast()
            }
        }
    }

    private static var _lazyISolidColorBrushStatics: COM.COMReference<SWRT_MicrosoftUIXamlMedia_ISolidColorBrushStatics>.Optional = .none

    internal static var _isolidColorBrushStatics: COM.COMInterop<SWRT_MicrosoftUIXamlMedia_ISolidColorBrushStatics> {
        get throws {
            try _lazyISolidColorBrushStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_MicrosoftUIXamlMedia_ISolidColorBrushStatics.self)).cast()
            }
        }
    }
}