// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Defines the type of text edit change.
public struct MicrosoftUIXamlAutomation_AutomationTextEditChangeType: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Not related to a specific change type.
    public static let none = Self()

    /// Change is from an auto-correct action performed by a control.
    public static let autoCorrect = Self(rawValue: 1)

    /// Change is from an IME active composition within a control.
    public static let composition = Self(rawValue: 2)

    /// Change is from an IME composition going from active to finalized state within a control.
    public static let compositionFinalized = Self(rawValue: 3)
}