// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Contains the arguments returned by the last pointer event.
public final class WindowsUICore_PointerEventArgs: WindowsRuntime.WinRTImport<WindowsUICore_PointerEventArgsBinding>, WindowsUICore_ICoreWindowEventArgsProtocol {
    /// Retrieves the pointer data for up to the last 64 pointer locations since the last pointer event.
    /// - Returns: The data for each pointer.
    public func getIntermediatePoints() throws -> WindowsFoundationCollections_IVector<WindowsUIInput_PointerPoint?> {
        try COM.NullResult.unwrap(_interop.getIntermediatePoints())
    }

    /// Information about the state and screen position of the pointer.
    public var currentPoint: WindowsUIInput_PointerPoint {
        get throws {
            try COM.NullResult.unwrap(_interop.get_CurrentPoint())
        }
    }

    /// Gets the pointer data of the last pointer event.
    public var currentPoint_: WindowsUIInput_PointerPoint! {
        try! NullResult.catch(self.currentPoint)
    }

    /// The active key modifiers.
    public var keyModifiers: WindowsSystem_VirtualKeyModifiers {
        get throws {
            try _interop.get_KeyModifiers()
        }
    }

    /// Gets the keyboard key or keys used to modify the pointer input, such as the "Ctrl" key when pressed in conjunction with another key, as in Ctrl+C.
    public var keyModifiers_: WindowsSystem_VirtualKeyModifiers {
        try! self.keyModifiers
    }

    // MARK: Windows.UI.Core.ICoreWindowEventArgs members

    /// True if the pointer event has been handled by the appropriate delegate; false if it has not.
    public var handled: Swift.Bool {
        get throws {
            try _icoreWindowEventArgs.get_Handled()
        }
    }

    /// Sets whether the pointer event was handled.
    /// - Parameter newValue: True if the pointer event has been handled by the appropriate delegate; false if it has not.
    public func handled(_ value: Swift.Bool) throws {
        try _icoreWindowEventArgs.put_Handled(value)
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsUICore_IPointerEventArgs>) {
        super.init(_wrapping: consume inner)
    }

    private var _lazyICoreWindowEventArgs: COM.COMReference<SWRT_WindowsUICore_ICoreWindowEventArgs>.Optional = .none

    internal var _icoreWindowEventArgs: COM.COMInterop<SWRT_WindowsUICore_ICoreWindowEventArgs> {
        get throws {
            try _lazyICoreWindowEventArgs.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUICore_ICoreWindowEventArgs.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.UI.Core.PointerEventArgs")
            }
        }
    }
}