// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Specifies the set of cursor types.
public struct WindowsUICore_CoreCursorType: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The left-upward (northwest) arrow Windows cursor.
    public static let arrow = Self()

    /// The "cross" Windows cursor.
    public static let cross = Self(rawValue: 1)

    /// A custom cursor.
    public static let custom = Self(rawValue: 2)

    /// The "hand" Windows cursor.
    public static let hand = Self(rawValue: 3)

    /// The left-upward (northwest) arrow Windows cursor with a question mark.
    public static let help = Self(rawValue: 4)

    /// The "I"-shaped Windows cursor used for text selection.
    public static let ibeam = Self(rawValue: 5)

    /// The "cross arrow" Windows cursor used for user interface (UI) element sizing.
    public static let sizeAll = Self(rawValue: 6)

    /// The "right-upward, left-downward" dual arrow Windows cursor often used for element sizing.
    public static let sizeNortheastSouthwest = Self(rawValue: 7)

    /// The up-down dual arrow Windows cursor often used for vertical (height) sizing.
    public static let sizeNorthSouth = Self(rawValue: 8)

    /// The "left-upward, right-downward" dual arrow Windows cursor often used for element sizing.
    public static let sizeNorthwestSoutheast = Self(rawValue: 9)

    /// The left-right dual arrow Windows cursor often used for horizontal (width) sizing.
    public static let sizeWestEast = Self(rawValue: 10)

    /// The red "circle slash" Windows cursor often used to indicate that a UI behavor cannot be performed.
    public static let universalNo = Self(rawValue: 11)

    /// The up arrow Windows cursor.
    public static let upArrow = Self(rawValue: 12)

    /// The cycling Windows "wait" cursor often used to indicate that an element or behavior is in a wait state and cannot respond at the time.
    public static let wait = Self(rawValue: 13)

    /// The "hand" Windows cursor with a pin symbol.
    public static let pin = Self(rawValue: 14)

    /// The "hand" Windows cursor with a person symbol.
    public static let person = Self(rawValue: 15)
}