// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Provides the Windows Runtime core event message dispatcher. Instances of this type are responsible for processing the window messages and dispatching the events to the client.
public final class WindowsUICore_CoreDispatcher: WindowsRuntime.WinRTImport<WindowsUICore_CoreDispatcherBinding>, WindowsUICore_ICoreAcceleratorKeysProtocol, @unchecked Sendable {
    /// Starts the dispatcher processing the input event queue for this instance of CoreWindow.
    /// - Parameter options: Determines how many events to process, and if this method should block.
    public func processEvents(_ options: WindowsUICore_CoreProcessEventsOption) throws {
        try _interop.processEvents(options)
    }

    /// Schedules the provided callback on the UI thread from a worker thread, and returns the results asynchronously.
    /// - Parameter priority: Specifies the priority for event dispatch. Set this to CoreDispatcherPriority.Normal.
    /// - Parameter agileCallback: The callback on which the dispatcher returns when the event is dispatched.
    /// - Returns: The object that provides handlers for the completed async event dispatch.
    public func runAsync(_ priority: WindowsUICore_CoreDispatcherPriority, _ agileCallback: WindowsUICore_DispatchedHandler?) throws -> WindowsFoundation_IAsyncAction {
        try COM.NullResult.unwrap(_interop.runAsync(priority, agileCallback))
    }

    /// Schedules a callback on the UI thread from a worker thread at idle priority, and returns the results asynchronously.
    /// - Parameter agileCallback: The callback on which the idle priority dispatcher returns when the event is dispatched.
    /// - Returns: Object that contains the results of the asynchronous action.
    public func runIdleAsync(_ agileCallback: WindowsUICore_IdleDispatchedHandler?) throws -> WindowsFoundation_IAsyncAction {
        try COM.NullResult.unwrap(_interop.runIdleAsync(agileCallback))
    }

    /// True if the event dispatcher has thread access; false it does not.
    public var hasThreadAccess: Swift.Bool {
        get throws {
            try _interop.get_HasThreadAccess()
        }
    }

    /// Gets a value that specifies whether the event dispatcher provided by this instance of CoreWindow has access to the current thread or not.
    public var hasThreadAccess_: Swift.Bool {
        try! self.hasThreadAccess
    }

    // MARK: Windows.UI.Core.ICoreAcceleratorKeys members

    /// Fired when an accelerator key is activated (pressed or held down).
    @discardableResult
    public func acceleratorKeyActivated(adding handler: WindowsFoundation_TypedEventHandler<WindowsUICore_CoreDispatcher?, WindowsUICore_AcceleratorKeyEventArgs?>?) throws -> WindowsRuntime.EventRegistration {
        let _token = try _icoreAcceleratorKeys.add_AcceleratorKeyActivated(handler)
        return WindowsRuntime.EventRegistration(source: self, token: _token, remover: { this, token in try (this as! Self).acceleratorKeyActivated(removing: token) })
    }

    public func acceleratorKeyActivated(removing cookie: WindowsRuntime.EventRegistrationToken) throws {
        try _icoreAcceleratorKeys.remove_AcceleratorKeyActivated(cookie)
    }

    /// Queries whether the caller should yield if there are items in the task queue of higher priority than the current task.
    /// - Returns: **true** if the current work item should yield to higher priority work; **false** if it should not.
    public func shouldYield() throws -> Swift.Bool {
        try _icoreDispatcherWithTaskPriority.shouldYield()
    }

    /// Queries whether the caller should yield if there are items in the task queue of the specified priority or higher.
    /// - Parameter priority: The minimum priority level for which the current work item should yield.
    /// - Returns: **true** if the current work item should yield to higher priority work; **false** if it should not.
    public func shouldYield(_ priority: WindowsUICore_CoreDispatcherPriority) throws -> Swift.Bool {
        try _icoreDispatcherWithTaskPriority.shouldYieldToPriority(priority)
    }

    /// Stops the dispatcher from processing any queued events.
    public func stopProcessEvents() throws {
        try _icoreDispatcherWithTaskPriority.stopProcessEvents()
    }

    /// A CoreDispatcherPriority enumeration value that specifies the priority of the current task.
    public var currentPriority: WindowsUICore_CoreDispatcherPriority {
        get throws {
            try _icoreDispatcherWithTaskPriority.get_CurrentPriority()
        }
    }

    /// Gets and sets the priority of the current task.
    /// - Parameter newValue: A CoreDispatcherPriority enumeration value that specifies the priority of the current task.
    public func currentPriority(_ value: WindowsUICore_CoreDispatcherPriority) throws {
        try _icoreDispatcherWithTaskPriority.put_CurrentPriority(value)
    }

    /// Gets and sets the priority of the current task.
    public var currentPriority_: WindowsUICore_CoreDispatcherPriority {
        get {
            try! self.currentPriority
        }
        set {
            try! self.currentPriority(newValue)
        }
    }

    /// Attempts to schedule the specified callback on the UI thread from a worker thread, and returns the results asynchronously.
    /// - Parameter priority: Specifies the priority for event dispatch. Set this to CoreDispatcherPriority.Normal.
    /// - Parameter agileCallback: The callback on which the dispatcher returns when the event is dispatched.
    /// - Returns: The asynchronous operation.
    public func tryRunAsync(_ priority: WindowsUICore_CoreDispatcherPriority, _ agileCallback: WindowsUICore_DispatchedHandler?) throws -> WindowsFoundation_IAsyncOperation<Swift.Bool> {
        try COM.NullResult.unwrap(_icoreDispatcher2.tryRunAsync(priority, agileCallback))
    }

    /// Attempts to schedule a callback on the UI thread from a worker thread at idle priority, and returns the results asynchronously.
    /// - Parameter agileCallback: The callback on which the idle priority dispatcher returns when the event is dispatched.
    /// - Returns: The asynchronous operation.
    public func tryRunIdleAsync(_ agileCallback: WindowsUICore_IdleDispatchedHandler?) throws -> WindowsFoundation_IAsyncOperation<Swift.Bool> {
        try COM.NullResult.unwrap(_icoreDispatcher2.tryRunIdleAsync(agileCallback))
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsUICore_ICoreDispatcher>) {
        super.init(_wrapping: consume inner)
    }

    private var _lazyICoreAcceleratorKeys: COM.COMReference<SWRT_WindowsUICore_ICoreAcceleratorKeys>.Optional = .none

    internal var _icoreAcceleratorKeys: COM.COMInterop<SWRT_WindowsUICore_ICoreAcceleratorKeys> {
        get throws {
            try _lazyICoreAcceleratorKeys.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUICore_ICoreAcceleratorKeys.self)).cast()
            }
        }
    }

    private var _lazyICoreDispatcherWithTaskPriority: COM.COMReference<SWRT_WindowsUICore_ICoreDispatcherWithTaskPriority>.Optional = .none

    internal var _icoreDispatcherWithTaskPriority: COM.COMInterop<SWRT_WindowsUICore_ICoreDispatcherWithTaskPriority> {
        get throws {
            try _lazyICoreDispatcherWithTaskPriority.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUICore_ICoreDispatcherWithTaskPriority.self)).cast()
            }
        }
    }

    private var _lazyICoreDispatcher2: COM.COMReference<SWRT_WindowsUICore_ICoreDispatcher2>.Optional = .none

    internal var _icoreDispatcher2: COM.COMInterop<SWRT_WindowsUICore_ICoreDispatcher2> {
        get throws {
            try _lazyICoreDispatcher2.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUICore_ICoreDispatcher2.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.UI.Core.CoreDispatcher")
            }
        }
    }
}