// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Enables the calling app to read through the changes to items in a storage library.
public final class WindowsStorage_StorageLibraryChangeReader: WindowsRuntime.WinRTImport<WindowsStorage_StorageLibraryChangeReaderBinding>, @unchecked Sendable {
    /// Asynchronously gets a list of StorageLibraryChange objects.
    /// - Returns: A list of StorageLibraryChange objects.
    public func readBatchAsync() throws -> WindowsFoundation_IAsyncOperation<WindowsFoundationCollections_IVectorView<WindowsStorage_StorageLibraryChange?>?> {
        try COM.NullResult.unwrap(_interop.readBatchAsync())
    }

    /// Tells the system that all of the changes described in the StorageLibraryChange objects returned by the call to ReadBatchAsync have been addressed by the app.
    /// - Returns: An object that is used to manage the asynchronous accept change operation.
    public func acceptChangesAsync() throws -> WindowsFoundation_IAsyncAction {
        try COM.NullResult.unwrap(_interop.acceptChangesAsync())
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsStorage_IStorageLibraryChangeReader>) {
        super.init(_wrapping: consume inner)
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.Storage.StorageLibraryChangeReader")
            }
        }
    }
}