// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Specifies whether to access a file in read-only mode or in read/write mode.
public struct WindowsStorage_FileAccessMode: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Access the file stream in read-only mode.
    public static let read = Self()

    /// Access the file stream in read/write mode.
    public static let readWrite = Self(rawValue: 1)
}