// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Provides event information about whether an app is in pre-launch state.
public typealias WindowsApplicationModelActivation_IPrelaunchActivatedEventArgs = any WindowsApplicationModelActivation_IPrelaunchActivatedEventArgsProtocol


/// Provides event information about whether an app is in pre-launch state.
public protocol WindowsApplicationModelActivation_IPrelaunchActivatedEventArgsProtocol: WindowsApplicationModelActivation_IActivatedEventArgsProtocol {
    /// Indicates whether a pre-launch has been activated. **TRUE** indicates activated; otherwise, **FALSE**.
    var prelaunchActivated: Swift.Bool { get throws }
}

extension WindowsApplicationModelActivation_IPrelaunchActivatedEventArgsProtocol {
    /// Gets an indication about whether a pre-launch has been activated.
    public var prelaunchActivated_: Swift.Bool {
        try! self.prelaunchActivated
    }
}