// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlControls_ColumnDefinitionCollectionBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlControls_ColumnDefinitionCollection
    public typealias ABIStruct = SWRT_WindowsFoundationCollections_IVector_MicrosoftUIXamlControls_ColumnDefinition

    public static let typeName = "Microsoft.UI.Xaml.Controls.ColumnDefinitionCollection"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlControls_ColumnDefinitionCollection(_wrapping: consume reference)
    }
}