// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlControls_ItemClickEventArgsBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlControls_ItemClickEventArgs
    public typealias ABIStruct = SWRT_MicrosoftUIXamlControls_IItemClickEventArgs

    public static let typeName = "Microsoft.UI.Xaml.Controls.ItemClickEventArgs"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlControls_ItemClickEventArgs(_wrapping: consume reference)
    }
}