// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

extension MicrosoftUIXamlControls_BackgroundSizing: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Microsoft.UI.Xaml.Controls.BackgroundSizing"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x427926B5, 0x2AA4, 0x5EC7, 0xB979, 0xF892B69C881F)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x40AD11A5, 0x7E1C, 0x57A2, 0x9791, 0xBFB677E9589D)
    }
}