// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// A callback that will be executed on the **DispatcherQueue** thread.
public typealias WindowsSystem_DispatcherQueueHandler = () throws -> Swift.Void