// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

extension WindowsUICore_CoreProcessEventsOption: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Windows.UI.Core.CoreProcessEventsOption"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x4DF35F43, 0xFF76, 0x5633, 0xAA71, 0xADBF2DCB1B56)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x1F1D1C5E, 0x2C09, 0x5D70, 0x824C, 0xB081D0EC9981)
    }
}