// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsUICore_CoreWindowEventArgsBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = WindowsUICore_CoreWindowEventArgs
    public typealias ABIStruct = SWRT_WindowsUICore_ICoreWindowEventArgs

    public static let typeName = "Windows.UI.Core.CoreWindowEventArgs"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsUICore_CoreWindowEventArgs(_wrapping: consume reference)
    }
}