// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Defines a flexible grid area that consists of columns and rows. Child elements of the Grid are measured and arranged according to their row/column assignments (set by using Grid.Row and Grid.Column attached properties) and other logic.
open class MicrosoftUIXamlControls_Grid: MicrosoftUIXamlControls_Panel, @unchecked Sendable {
    /// Initializes a new instance of the Grid class.
    public override init() throws {
        try super.init(_compose: Self.self != MicrosoftUIXamlControls_Grid.self) {
            (baseInterface, innerInterface: inout IInspectablePointer?) in
            try Self._igridFactory.createInstance(baseInterface, &innerInterface)
        }
    }

    /// A value of the enumeration that indicates how far the background extends. The default is InnerBorderEdge.
    public var backgroundSizing: MicrosoftUIXamlControls_BackgroundSizing {
        get throws {
            try _igrid.get_BackgroundSizing()
        }
    }

    /// Sets a value that indicates how far the background extends in relation to this element's border.
    /// - Parameter newValue: A value of the enumeration that indicates how far the background extends. The default is InnerBorderEdge.
    public func backgroundSizing(_ value: MicrosoftUIXamlControls_BackgroundSizing) throws {
        try _igrid.put_BackgroundSizing(value)
    }

    /// Gets or sets a value that indicates how far the background extends in relation to this element's border.
    public var backgroundSizing_: MicrosoftUIXamlControls_BackgroundSizing {
        get {
            try! self.backgroundSizing
        }
        set {
            try! self.backgroundSizing(newValue)
        }
    }

    /// The brush that is used to fill the panel's border. The default is null, (a null brush) which is evaluated as Transparent for rendering.
    public var borderBrush: MicrosoftUIXamlMedia_Brush {
        get throws {
            try COM.NullResult.unwrap(_igrid.get_BorderBrush())
        }
    }

    /// Sets a brush that describes the border fill of the panel.
    /// - Parameter newValue: The brush that is used to fill the panel's border. The default is null, (a null brush) which is evaluated as Transparent for rendering.
    public func borderBrush(_ value: MicrosoftUIXamlMedia_Brush?) throws {
        try _igrid.put_BorderBrush(value)
    }

    /// Gets or sets a brush that describes the border fill of the panel.
    public var borderBrush_: MicrosoftUIXamlMedia_Brush! {
        get {
            try! NullResult.catch(self.borderBrush)
        }
        set {
            try! self.borderBrush(newValue)
        }
    }

    /// The border thickness of the panel, as a Thickness value.
    public var borderThickness: MicrosoftUIXaml_Thickness {
        get throws {
            try _igrid.get_BorderThickness()
        }
    }

    /// Sets the border thickness of the panel.
    /// - Parameter newValue: The border thickness of the panel, as a Thickness value.
    public func borderThickness(_ value: MicrosoftUIXaml_Thickness) throws {
        try _igrid.put_BorderThickness(value)
    }

    /// Gets or sets the border thickness of the panel.
    public var borderThickness_: MicrosoftUIXaml_Thickness {
        get {
            try! self.borderThickness
        }
        set {
            try! self.borderThickness(newValue)
        }
    }

    /// A list of ColumnDefinition objects defined on this instance of Grid.
    public var columnDefinitions: MicrosoftUIXamlControls_ColumnDefinitionCollection {
        get throws {
            try COM.NullResult.unwrap(_igrid.get_ColumnDefinitions())
        }
    }

    /// Gets a list of ColumnDefinition objects defined on this instance of Grid.
    public var columnDefinitions_: MicrosoftUIXamlControls_ColumnDefinitionCollection! {
        try! NullResult.catch(self.columnDefinitions)
    }

    /// The uniform distance (in pixels) between grid columns.
    public var columnSpacing: Swift.Double {
        get throws {
            try _igrid.get_ColumnSpacing()
        }
    }

    /// Sets the uniform distance (in pixels) between grid columns.
    /// - Parameter newValue: The uniform distance (in pixels) between grid columns.
    public func columnSpacing(_ value: Swift.Double) throws {
        try _igrid.put_ColumnSpacing(value)
    }

    /// Gets or sets the uniform distance (in pixels) between grid columns.
    public var columnSpacing_: Swift.Double {
        get {
            try! self.columnSpacing
        }
        set {
            try! self.columnSpacing(newValue)
        }
    }

    /// The degree to which the corners are rounded, expressed as values of the CornerRadius structure.
    public var cornerRadius: MicrosoftUIXaml_CornerRadius {
        get throws {
            try _igrid.get_CornerRadius()
        }
    }

    /// Sets the radius for the corners of the panel's border.
    /// - Parameter newValue: The degree to which the corners are rounded, expressed as values of the CornerRadius structure.
    public func cornerRadius(_ value: MicrosoftUIXaml_CornerRadius) throws {
        try _igrid.put_CornerRadius(value)
    }

    /// Gets or sets the radius for the corners of the panel's border.
    public var cornerRadius_: MicrosoftUIXaml_CornerRadius {
        get {
            try! self.cornerRadius
        }
        set {
            try! self.cornerRadius(newValue)
        }
    }

    /// The dimensions of the space between the border and its child as a Thickness value. Thickness is a structure that stores dimension values using pixel measures.
    public var padding: MicrosoftUIXaml_Thickness {
        get throws {
            try _igrid.get_Padding()
        }
    }

    /// Sets the distance between the border and its child object.
    /// - Parameter newValue: The dimensions of the space between the border and its child as a Thickness value. Thickness is a structure that stores dimension values using pixel measures.
    public func padding(_ value: MicrosoftUIXaml_Thickness) throws {
        try _igrid.put_Padding(value)
    }

    /// Gets or sets the distance between the border and its child object.
    public var padding_: MicrosoftUIXaml_Thickness {
        get {
            try! self.padding
        }
        set {
            try! self.padding(newValue)
        }
    }

    /// A list of RowDefinition objects defined on this instance of Grid.
    public var rowDefinitions: MicrosoftUIXamlControls_RowDefinitionCollection {
        get throws {
            try COM.NullResult.unwrap(_igrid.get_RowDefinitions())
        }
    }

    /// Gets a list of RowDefinition objects defined on this instance of Grid.
    public var rowDefinitions_: MicrosoftUIXamlControls_RowDefinitionCollection! {
        try! NullResult.catch(self.rowDefinitions)
    }

    /// The uniform distance (in pixels) between grid rows.
    public var rowSpacing: Swift.Double {
        get throws {
            try _igrid.get_RowSpacing()
        }
    }

    /// Sets the uniform distance (in pixels) between grid rows.
    /// - Parameter newValue: The uniform distance (in pixels) between grid rows.
    public func rowSpacing(_ value: Swift.Double) throws {
        try _igrid.put_RowSpacing(value)
    }

    /// Gets or sets the uniform distance (in pixels) between grid rows.
    public var rowSpacing_: Swift.Double {
        get {
            try! self.rowSpacing
        }
        set {
            try! self.rowSpacing(newValue)
        }
    }

    /// Gets the value of the Grid.Row XAML attached property from the specified FrameworkElement.
    /// - Parameter element: The element from which to read the property value.
    /// - Returns: The value of the Grid.Row XAML attached property on the target element.
    public static func getRow(_ element: MicrosoftUIXaml_FrameworkElement?) throws -> Swift.Int32 {
        try _igridStatics.getRow(element)
    }

    /// Sets the value of the Grid.Row XAML attached property on the specified FrameworkElement.
    /// - Parameter element: The target element on which to set the Grid.Row XAML attached property.
    /// - Parameter value: The property value to set.
    public static func setRow(_ element: MicrosoftUIXaml_FrameworkElement?, _ value: Swift.Int32) throws {
        try _igridStatics.setRow(element, value)
    }

    /// Gets the value of the Grid.Column XAML attached property from the specified FrameworkElement.
    /// - Parameter element: The element from which to read the property value.
    /// - Returns: The value of the Grid.Column XAML attached property on the target element. This is a zero-based index.
    public static func getColumn(_ element: MicrosoftUIXaml_FrameworkElement?) throws -> Swift.Int32 {
        try _igridStatics.getColumn(element)
    }

    /// Sets the value of the Grid.Column XAML attached property on the specified FrameworkElement.
    /// - Parameter element: The target element on which to set the Grid.Column XAML attached property.
    /// - Parameter value: The property value to set.
    public static func setColumn(_ element: MicrosoftUIXaml_FrameworkElement?, _ value: Swift.Int32) throws {
        try _igridStatics.setColumn(element, value)
    }

    /// Gets the value of the Grid.RowSpan XAML attached property from the specified FrameworkElement.
    /// - Parameter element: The element from which to read the property value.
    /// - Returns: The value of the Grid.RowSpan XAML attached property on the target element.
    public static func getRowSpan(_ element: MicrosoftUIXaml_FrameworkElement?) throws -> Swift.Int32 {
        try _igridStatics.getRowSpan(element)
    }

    /// Sets the value of the Grid.RowSpan XAML attached property on the specified FrameworkElement.
    /// - Parameter element: The target element on which to set the Grid.RowSpan XAML attached property.
    /// - Parameter value: The property value to set.
    public static func setRowSpan(_ element: MicrosoftUIXaml_FrameworkElement?, _ value: Swift.Int32) throws {
        try _igridStatics.setRowSpan(element, value)
    }

    /// Gets the value of the Grid.ColumnSpan XAML attached property from the specified FrameworkElement.
    /// - Parameter element: The element from which to read the property value.
    /// - Returns: The value of the Grid.ColumnSpan XAML attached property on the target element.
    public static func getColumnSpan(_ element: MicrosoftUIXaml_FrameworkElement?) throws -> Swift.Int32 {
        try _igridStatics.getColumnSpan(element)
    }

    /// Sets the value of the Grid.ColumnSpan XAML attached property on the specified FrameworkElement.
    /// - Parameter element: The element on which to set the Grid.ColumnSpan XAML attached property.
    /// - Parameter value: The property value to set.
    public static func setColumnSpan(_ element: MicrosoftUIXaml_FrameworkElement?, _ value: Swift.Int32) throws {
        try _igridStatics.setColumnSpan(element, value)
    }

    /// The identifier for the BackgroundSizing dependency property.
    public static var backgroundSizingProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_BackgroundSizingProperty())
        }
    }

    /// Identifies the BackgroundSizing dependency property.
    public static var backgroundSizingProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.backgroundSizingProperty)
    }

    /// The identifier for the BorderBrush dependency property.
    public static var borderBrushProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_BorderBrushProperty())
        }
    }

    /// Identifies the BorderBrush dependency property.
    public static var borderBrushProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.borderBrushProperty)
    }

    /// The identifier for the BorderThickness dependency property.
    public static var borderThicknessProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_BorderThicknessProperty())
        }
    }

    /// Identifies the BorderThickness dependency property.
    public static var borderThicknessProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.borderThicknessProperty)
    }

    /// The identifier for the Grid.Column XAML attached property.
    public static var columnProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_ColumnProperty())
        }
    }

    /// Identifies the Grid.Column XAML attached property.
    public static var columnProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.columnProperty)
    }

    /// The identifier for the ColumnSpacing dependency property.
    public static var columnSpacingProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_ColumnSpacingProperty())
        }
    }

    /// Identifies the ColumnSpacing dependency property.
    public static var columnSpacingProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.columnSpacingProperty)
    }

    /// The identifier for the Grid.ColumnSpan XAML attached property.
    public static var columnSpanProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_ColumnSpanProperty())
        }
    }

    /// Identifies the Grid.ColumnSpan XAML attached property.
    public static var columnSpanProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.columnSpanProperty)
    }

    /// The identifier for the CornerRadius dependency property.
    public static var cornerRadiusProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_CornerRadiusProperty())
        }
    }

    /// Identifies the CornerRadius dependency property.
    public static var cornerRadiusProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.cornerRadiusProperty)
    }

    /// The identifier for the Padding dependency property.
    public static var paddingProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_PaddingProperty())
        }
    }

    /// Identifies the Padding dependency property.
    public static var paddingProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.paddingProperty)
    }

    /// The identifier for the Grid.Row XAML attached property.
    public static var rowProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_RowProperty())
        }
    }

    /// Identifies the Grid.Row XAML attached property.
    public static var rowProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.rowProperty)
    }

    /// The identifier for the RowSpacing dependency property.
    public static var rowSpacingProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_RowSpacingProperty())
        }
    }

    /// Identifies the RowSpacing dependency property.
    public static var rowSpacingProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.rowSpacingProperty)
    }

    /// The identifier for the Grid.RowSpan XAML attached property.
    public static var rowSpanProperty: MicrosoftUIXaml_DependencyProperty {
        get throws {
            try COM.NullResult.unwrap(_igridStatics.get_RowSpanProperty())
        }
    }

    /// Identifies the Grid.RowSpan XAML attached property.
    public static var rowSpanProperty_: MicrosoftUIXaml_DependencyProperty! {
        try! NullResult.catch(Self.rowSpanProperty)
    }

    // MARK: Implementation details

    public init(_wrapping inner: consuming COM.COMReference<SWRT_MicrosoftUIXamlControls_IGrid>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    public override init<ABIStruct>(_compose: Swift.Bool, _factory: ComposableFactory<ABIStruct>) throws {
        try super.init(_compose: _compose, _factory: _factory)
    }

    private var _lazyIGrid: COM.COMReference<SWRT_MicrosoftUIXamlControls_IGrid>.Optional = .none

    internal var _igrid: COM.COMInterop<SWRT_MicrosoftUIXamlControls_IGrid> {
        get throws {
            try _lazyIGrid.lazyInitInterop {
                try _queryInnerInterface(uuidof(SWRT_MicrosoftUIXamlControls_IGrid.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Microsoft.UI.Xaml.Controls.Grid")
            }
        }
    }

    private static var _lazyIGridFactory: COM.COMReference<SWRT_MicrosoftUIXamlControls_IGridFactory>.Optional = .none

    internal static var _igridFactory: COM.COMInterop<SWRT_MicrosoftUIXamlControls_IGridFactory> {
        get throws {
            try _lazyIGridFactory.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_MicrosoftUIXamlControls_IGridFactory.self)).cast()
            }
        }
    }

    private static var _lazyIGridStatics: COM.COMReference<SWRT_MicrosoftUIXamlControls_IGridStatics>.Optional = .none

    internal static var _igridStatics: COM.COMInterop<SWRT_MicrosoftUIXamlControls_IGridStatics> {
        get throws {
            try _lazyIGridStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_MicrosoftUIXamlControls_IGridStatics.self)).cast()
            }
        }
    }
}