// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Defines constants that specify how far an element's background extends in relation to the element's border.
public struct MicrosoftUIXamlControls_BackgroundSizing: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The element's background extends to the inner edge of the border, but does not extend under the border.
    public static let innerBorderEdge = Self()

    /// The element's background extends under the border to its outer edge, and is visible if the border is transparent.
    public static let outerBorderEdge = Self(rawValue: 1)
}