// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftUIComposition_CompositionShapeCollectionBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIComposition_CompositionShapeCollection
    public typealias ABIStruct = SWRT_WindowsFoundationCollections_IVector_MicrosoftUIComposition_CompositionShape

    public static let typeName = "Microsoft.UI.Composition.CompositionShapeCollection"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIComposition_CompositionShapeCollection(_wrapping: consume reference)
    }
}