// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

extension MicrosoftUIComposition_CompositionStrokeCap: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Microsoft.UI.Composition.CompositionStrokeCap"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x2B83F15E, 0xC477, 0x5F7A, 0xAAB5, 0xC2517980D701)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xFA4944CF, 0xB013, 0x59E0, 0xAB8C, 0x6FBF0084636D)
    }
}