// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftUIComposition_CompositionProjectedShadowCasterBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIComposition_CompositionProjectedShadowCaster
    public typealias ABIStruct = SWRT_MicrosoftUIComposition_ICompositionProjectedShadowCaster

    public static let typeName = "Microsoft.UI.Composition.CompositionProjectedShadowCaster"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIComposition_CompositionProjectedShadowCaster(_wrapping: consume reference)
    }
}