// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftUIComposition_LayerVisualBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIComposition_LayerVisual
    public typealias ABIStruct = SWRT_MicrosoftUIComposition_ILayerVisual

    public static let typeName = "Microsoft.UI.Composition.LayerVisual"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIComposition_LayerVisual(_wrapping: consume reference)
    }
}