// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

extension MicrosoftUIComposition_CompositionBatchTypes: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Microsoft.UI.Composition.CompositionBatchTypes"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x1AF671F5, 0x526D, 0x5431, 0xBAD2, 0x1F8A48990296)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xDE64E3DA, 0x7124, 0x50BA, 0xAEF8, 0xA1C7A114D1DA)
    }
}