// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftUIComposition_CompositionStrokeDashArrayBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIComposition_CompositionStrokeDashArray
    public typealias ABIStruct = SWRT_WindowsFoundationCollections_IVector_Float

    public static let typeName = "Microsoft.UI.Composition.CompositionStrokeDashArray"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIComposition_CompositionStrokeDashArray(_wrapping: consume reference)
    }
}