// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftUIComposition_CompositionGeometryBinding: WindowsRuntime.ComposableClassBinding {
    public typealias SwiftObject = MicrosoftUIComposition_CompositionGeometry
    public typealias ABIStruct = SWRT_MicrosoftUIComposition_ICompositionGeometry

    public static let typeName = "Microsoft.UI.Composition.CompositionGeometry"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIComposition_CompositionGeometry(_wrapping: consume reference)
    }
}