// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftUIComposition_StepEasingFunctionBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIComposition_StepEasingFunction
    public typealias ABIStruct = SWRT_MicrosoftUIComposition_IStepEasingFunction

    public static let typeName = "Microsoft.UI.Composition.StepEasingFunction"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIComposition_StepEasingFunction(_wrapping: consume reference)
    }
}