// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public enum MicrosoftUIComposition_IVisualElement2Binding: WindowsRuntime.InterfaceBinding {
    public typealias SwiftObject = MicrosoftUIComposition_IVisualElement2
    public typealias ABIStruct = SWRT_MicrosoftUIComposition_IVisualElement2

    public static let typeName = "Microsoft.UI.Composition.IVisualElement2"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        Import(_wrapping: consume reference)
    }

    private final class Import: WinRTImport<MicrosoftUIComposition_IVisualElement2Binding>, MicrosoftUIComposition_IVisualElement2Protocol {
        public func getVisualInternal() throws -> MicrosoftUIComposition_Visual {
            try COM.NullResult.unwrap(_interop.getVisualInternal())
        }
    }

    public static var virtualTablePointer: UnsafeRawPointer {
        .init(withUnsafePointer(to: &virtualTable) { $0 })
    }

    private static var virtualTable = SWRT_MicrosoftUIComposition_IVisualElement2_VirtualTable(
        QueryInterface: { IUnknownVirtualTable.QueryInterface($0, $1, $2) },
        AddRef: { IUnknownVirtualTable.AddRef($0) },
        Release: { IUnknownVirtualTable.Release($0) },
        GetIids: { IInspectableVirtualTable.GetIids($0, $1, $2) },
        GetRuntimeClassName: { IInspectableVirtualTable.GetRuntimeClassName($0, $1) },
        GetTrustLevel: { IInspectableVirtualTable.GetTrustLevel($0, $1) },
        GetVisualInternal: { this, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let _result_swift = try COM.NullResult.`catch`(try this.getVisualInternal())
            _result.pointee = try MicrosoftUIComposition_VisualBinding.toABI(_result_swift)
        } }
    )
}