// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

extension WindowsUIText_FontStyle: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Windows.UI.Text.FontStyle"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0xBE68E421, 0xAB4E, 0x5DBF, 0x9FDE, 0x9B8C13CB5F0A)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x5E85E63B, 0x1B8F, 0x571A, 0x941F, 0x60A5FC36EB73)
    }
}