// Generated by swift-winrt
// swiftlint:disable all

import UWP

public typealias CollectionChange = WindowsFoundationCollections_CollectionChange
public typealias IIterable<T> = WindowsFoundationCollections_IIterable<T>

public protocol IIterableProtocol<T>: WindowsFoundationCollections_IIterableProtocol {
}

public typealias IIterableBinding = WindowsFoundationCollections_IIterableBinding
public typealias IIterator<T> = WindowsFoundationCollections_IIterator<T>

public protocol IIteratorProtocol<T>: WindowsFoundationCollections_IIteratorProtocol {
}

public typealias IIteratorBinding = WindowsFoundationCollections_IIteratorBinding
public typealias IKeyValuePair<K, V> = WindowsFoundationCollections_IKeyValuePair<K, V>

public protocol IKeyValuePairProtocol<K, V>: WindowsFoundationCollections_IKeyValuePairProtocol {
}

public typealias IKeyValuePairBinding = WindowsFoundationCollections_IKeyValuePairBinding
public typealias IMapChangedEventArgs<K> = WindowsFoundationCollections_IMapChangedEventArgs<K>

public protocol IMapChangedEventArgsProtocol<K>: WindowsFoundationCollections_IMapChangedEventArgsProtocol {
}

public typealias IMapChangedEventArgsBinding = WindowsFoundationCollections_IMapChangedEventArgsBinding
public typealias IMapView<K, V> = WindowsFoundationCollections_IMapView<K, V>

public protocol IMapViewProtocol<K, V>: WindowsFoundationCollections_IMapViewProtocol {
}

public typealias IMapViewBinding = WindowsFoundationCollections_IMapViewBinding
public typealias IMap<K, V> = WindowsFoundationCollections_IMap<K, V>

public protocol IMapProtocol<K, V>: WindowsFoundationCollections_IMapProtocol {
}

public typealias IMapBinding = WindowsFoundationCollections_IMapBinding
public typealias IObservableMap<K, V> = WindowsFoundationCollections_IObservableMap<K, V>

public protocol IObservableMapProtocol<K, V>: WindowsFoundationCollections_IObservableMapProtocol {
}

public typealias IObservableMapBinding = WindowsFoundationCollections_IObservableMapBinding
public typealias IObservableVector<T> = WindowsFoundationCollections_IObservableVector<T>

public protocol IObservableVectorProtocol<T>: WindowsFoundationCollections_IObservableVectorProtocol {
}

public typealias IObservableVectorBinding = WindowsFoundationCollections_IObservableVectorBinding
public typealias IPropertySet = WindowsFoundationCollections_IPropertySet

public protocol IPropertySetProtocol: WindowsFoundationCollections_IPropertySetProtocol {
}

public typealias IPropertySetBinding = WindowsFoundationCollections_IPropertySetBinding
public typealias IVectorChangedEventArgs = WindowsFoundationCollections_IVectorChangedEventArgs

public protocol IVectorChangedEventArgsProtocol: WindowsFoundationCollections_IVectorChangedEventArgsProtocol {
}

public typealias IVectorChangedEventArgsBinding = WindowsFoundationCollections_IVectorChangedEventArgsBinding
public typealias IVectorView<T> = WindowsFoundationCollections_IVectorView<T>

public protocol IVectorViewProtocol<T>: WindowsFoundationCollections_IVectorViewProtocol {
}

public typealias IVectorViewBinding = WindowsFoundationCollections_IVectorViewBinding
public typealias IVector<T> = WindowsFoundationCollections_IVector<T>

public protocol IVectorProtocol<T>: WindowsFoundationCollections_IVectorProtocol {
}

public typealias IVectorBinding = WindowsFoundationCollections_IVectorBinding
public typealias MapChangedEventHandler<K, V> = WindowsFoundationCollections_MapChangedEventHandler<K, V>
public typealias MapChangedEventHandlerBinding = WindowsFoundationCollections_MapChangedEventHandlerBinding
public typealias VectorChangedEventHandler<T> = WindowsFoundationCollections_VectorChangedEventHandler<T>
public typealias VectorChangedEventHandlerBinding = WindowsFoundationCollections_VectorChangedEventHandlerBinding