// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsSystem_UserBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = WindowsSystem_User
    public typealias ABIStruct = SWRT_WindowsSystem_IUser

    public static let typeName = "Windows.System.User"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsSystem_User(_wrapping: consume reference)
    }
}