// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlData_BindingExpressionBaseBinding: WindowsRuntime.ComposableClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlData_BindingExpressionBase
    public typealias ABIStruct = SWRT_MicrosoftUIXamlData_IBindingExpressionBase

    public static let typeName = "Microsoft.UI.Xaml.Data.BindingExpressionBase"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlData_BindingExpressionBase(_wrapping: consume reference)
    }
}