// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

extension MicrosoftUIXamlData_BindingMode: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Microsoft.UI.Xaml.Data.BindingMode"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x899C27C8, 0xF783, 0x52AE, 0x97B1, 0x386773457A30)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x88A1540F, 0x9CC2, 0x55EC, 0xA6E9, 0x1B90BD7AD9F3)
    }
}