// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

extension WindowsStorage_FileAttributes: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Windows.Storage.FileAttributes"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x7EFEFA72, 0xA793, 0x5E0C, 0xB3A9, 0x0A438B3E27D6)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x9F6330C4, 0x84B0, 0x57C5, 0x8021, 0x1BAC7DDEBD5D)
    }
}