// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsStorage_StorageStreamTransactionBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = WindowsStorage_StorageStreamTransaction
    public typealias ABIStruct = SWRT_WindowsStorage_IStorageStreamTransaction

    public static let typeName = "Windows.Storage.StorageStreamTransaction"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsStorage_StorageStreamTransaction(_wrapping: consume reference)
    }
}