// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP


/// Implements a set of predefined colors. See Color for usage information.
public final class MicrosoftUI_Colors: WindowsRuntime.WinRTImport<MicrosoftUI_ColorsBinding>, @unchecked Sendable {
    /// The system-defined color that has an ARGB value of #FFF0F8FF.
    public static var aliceBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_AliceBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF0F8FF.
    public static var aliceBlue_: WindowsUI_Color {
        try! Self.aliceBlue
    }

    /// The system-defined color that has an ARGB value of #FFFAEBD7.
    public static var antiqueWhite: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_AntiqueWhite()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFAEBD7.
    public static var antiqueWhite_: WindowsUI_Color {
        try! Self.antiqueWhite
    }

    /// The system-defined color that has an ARGB value of #FF00FFFF.
    public static var aqua: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Aqua()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF00FFFF.
    public static var aqua_: WindowsUI_Color {
        try! Self.aqua
    }

    /// The system-defined color that has an ARGB value of #FF7FFFD4.
    public static var aquamarine: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Aquamarine()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF7FFFD4.
    public static var aquamarine_: WindowsUI_Color {
        try! Self.aquamarine
    }

    /// The system-defined color that has an ARGB value of #FFF0FFFF.
    public static var azure: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Azure()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF0FFFF.
    public static var azure_: WindowsUI_Color {
        try! Self.azure
    }

    /// The system-defined color that has an ARGB value of #FFF5F5DC.
    public static var beige: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Beige()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF5F5DC.
    public static var beige_: WindowsUI_Color {
        try! Self.beige
    }

    /// The system-defined color that has an ARGB value of #FFFFE4C4.
    public static var bisque: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Bisque()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFE4C4.
    public static var bisque_: WindowsUI_Color {
        try! Self.bisque
    }

    /// The system-defined color that has the ARGB value of #FF000000.
    public static var black: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Black()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FF000000.
    public static var black_: WindowsUI_Color {
        try! Self.black
    }

    /// The system-defined color that has an ARGB value of #FFFFEBCD.
    public static var blanchedAlmond: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_BlanchedAlmond()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFEBCD.
    public static var blanchedAlmond_: WindowsUI_Color {
        try! Self.blanchedAlmond
    }

    /// The system-defined color that has the ARGB value of #FF0000FF.
    public static var blue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Blue()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FF0000FF.
    public static var blue_: WindowsUI_Color {
        try! Self.blue
    }

    /// The system-defined color that has an ARGB value of #FF8A2BE2.
    public static var blueViolet: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_BlueViolet()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF8A2BE2.
    public static var blueViolet_: WindowsUI_Color {
        try! Self.blueViolet
    }

    /// The system-defined color that has the ARGB value of #FFA52A2A.
    public static var brown: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Brown()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFA52A2A.
    public static var brown_: WindowsUI_Color {
        try! Self.brown
    }

    /// The system-defined color that has an ARGB value of #FFDEB887.
    public static var burlyWood: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_BurlyWood()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFDEB887.
    public static var burlyWood_: WindowsUI_Color {
        try! Self.burlyWood
    }

    /// The system-defined color that has an ARGB value of #FF5F9EA0.
    public static var cadetBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_CadetBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF5F9EA0.
    public static var cadetBlue_: WindowsUI_Color {
        try! Self.cadetBlue
    }

    /// The system-defined color that has an ARGB value of #FF7FFF00.
    public static var chartreuse: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Chartreuse()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF7FFF00.
    public static var chartreuse_: WindowsUI_Color {
        try! Self.chartreuse
    }

    /// The system-defined color that has an ARGB value of #FFD2691E.
    public static var chocolate: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Chocolate()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFD2691E.
    public static var chocolate_: WindowsUI_Color {
        try! Self.chocolate
    }

    /// The system-defined color that has an ARGB value of #FFFF7F50.
    public static var coral: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Coral()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFF7F50.
    public static var coral_: WindowsUI_Color {
        try! Self.coral
    }

    /// The system-defined color that has an ARGB value of #FF6495ED.
    public static var cornflowerBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_CornflowerBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF6495ED.
    public static var cornflowerBlue_: WindowsUI_Color {
        try! Self.cornflowerBlue
    }

    /// The system-defined color that has an ARGB value of #FFFFF8DC.
    public static var cornsilk: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Cornsilk()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFF8DC.
    public static var cornsilk_: WindowsUI_Color {
        try! Self.cornsilk
    }

    /// The system-defined color that has an ARGB value of #FFDC143C.
    public static var crimson: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Crimson()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFDC143C.
    public static var crimson_: WindowsUI_Color {
        try! Self.crimson
    }

    /// The system-defined color that has the ARGB value of ##FF00FFFF.
    public static var cyan: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Cyan()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FF00FFFF.
    public static var cyan_: WindowsUI_Color {
        try! Self.cyan
    }

    /// The system-defined color that has an ARGB value of #FF00008B.
    public static var darkBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF00008B.
    public static var darkBlue_: WindowsUI_Color {
        try! Self.darkBlue
    }

    /// The system-defined color that has an ARGB value of #FF008B8B.
    public static var darkCyan: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkCyan()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF008B8B.
    public static var darkCyan_: WindowsUI_Color {
        try! Self.darkCyan
    }

    /// The system-defined color that has an ARGB value of #FFB8860B.
    public static var darkGoldenrod: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkGoldenrod()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFB8860B.
    public static var darkGoldenrod_: WindowsUI_Color {
        try! Self.darkGoldenrod
    }

    /// The system-defined color that has the ARGB value of #FFA9A9A9.
    public static var darkGray: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkGray()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFA9A9A9.
    public static var darkGray_: WindowsUI_Color {
        try! Self.darkGray
    }

    /// The system-defined color that has an ARGB value of #FF006400.
    public static var darkGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF006400.
    public static var darkGreen_: WindowsUI_Color {
        try! Self.darkGreen
    }

    /// The system-defined color that has an ARGB value of #FFBDB76B.
    public static var darkKhaki: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkKhaki()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFBDB76B.
    public static var darkKhaki_: WindowsUI_Color {
        try! Self.darkKhaki
    }

    /// The system-defined color that has an ARGB value of #FF8B008B.
    public static var darkMagenta: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkMagenta()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF8B008B.
    public static var darkMagenta_: WindowsUI_Color {
        try! Self.darkMagenta
    }

    /// The system-defined color that has an ARGB value of #FF556B2F.
    public static var darkOliveGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkOliveGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF556B2F.
    public static var darkOliveGreen_: WindowsUI_Color {
        try! Self.darkOliveGreen
    }

    /// The system-defined color that has an ARGB value of #FFFF8C00.
    public static var darkOrange: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkOrange()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFF8C00.
    public static var darkOrange_: WindowsUI_Color {
        try! Self.darkOrange
    }

    /// The system-defined color that has an ARGB value of #FF9932CC.
    public static var darkOrchid: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkOrchid()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF9932CC.
    public static var darkOrchid_: WindowsUI_Color {
        try! Self.darkOrchid
    }

    /// The system-defined color that has an ARGB value of #FF8B0000.
    public static var darkRed: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkRed()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF8B0000.
    public static var darkRed_: WindowsUI_Color {
        try! Self.darkRed
    }

    /// The system-defined color that has an ARGB value of #FFE9967A.
    public static var darkSalmon: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkSalmon()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFE9967A.
    public static var darkSalmon_: WindowsUI_Color {
        try! Self.darkSalmon
    }

    /// The system-defined color that has an ARGB value of #FF8FBC8F.
    public static var darkSeaGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkSeaGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF8FBC8F.
    public static var darkSeaGreen_: WindowsUI_Color {
        try! Self.darkSeaGreen
    }

    /// The system-defined color that has an ARGB value of #FF483D8B.
    public static var darkSlateBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkSlateBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF483D8B.
    public static var darkSlateBlue_: WindowsUI_Color {
        try! Self.darkSlateBlue
    }

    /// The system-defined color that has an ARGB value of #FF2F4F4F.
    public static var darkSlateGray: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkSlateGray()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF2F4F4F.
    public static var darkSlateGray_: WindowsUI_Color {
        try! Self.darkSlateGray
    }

    /// The system-defined color that has an ARGB value of #FF00CED1.
    public static var darkTurquoise: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkTurquoise()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF00CED1.
    public static var darkTurquoise_: WindowsUI_Color {
        try! Self.darkTurquoise
    }

    /// The system-defined color that has an ARGB value of #FF9400D3.
    public static var darkViolet: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DarkViolet()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF9400D3.
    public static var darkViolet_: WindowsUI_Color {
        try! Self.darkViolet
    }

    /// The system-defined color that has an ARGB value of #FFFF1493.
    public static var deepPink: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DeepPink()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFF1493.
    public static var deepPink_: WindowsUI_Color {
        try! Self.deepPink
    }

    /// The system-defined color that has an ARGB value of #FF00BFFF.
    public static var deepSkyBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DeepSkyBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF00BFFF.
    public static var deepSkyBlue_: WindowsUI_Color {
        try! Self.deepSkyBlue
    }

    /// The system-defined color that has an ARGB value of #FF696969.
    public static var dimGray: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DimGray()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF696969.
    public static var dimGray_: WindowsUI_Color {
        try! Self.dimGray
    }

    /// The system-defined color that has an ARGB value of #FF1E90FF.
    public static var dodgerBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_DodgerBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF1E90FF.
    public static var dodgerBlue_: WindowsUI_Color {
        try! Self.dodgerBlue
    }

    /// The system-defined color that has an ARGB value of #FFB22222.
    public static var firebrick: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Firebrick()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFB22222.
    public static var firebrick_: WindowsUI_Color {
        try! Self.firebrick
    }

    /// The system-defined color that has an ARGB value of #FFFFFAF0.
    public static var floralWhite: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_FloralWhite()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFFAF0.
    public static var floralWhite_: WindowsUI_Color {
        try! Self.floralWhite
    }

    /// The system-defined color that has an ARGB value of #FF228B22.
    public static var forestGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_ForestGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF228B22.
    public static var forestGreen_: WindowsUI_Color {
        try! Self.forestGreen
    }

    /// The system-defined color that has an ARGB value of #FFFF00FF.
    public static var fuchsia: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Fuchsia()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFF00FF.
    public static var fuchsia_: WindowsUI_Color {
        try! Self.fuchsia
    }

    /// The system-defined color that has an ARGB value of #FFDCDCDC.
    public static var gainsboro: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Gainsboro()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFDCDCDC.
    public static var gainsboro_: WindowsUI_Color {
        try! Self.gainsboro
    }

    /// The system-defined color that has an ARGB value of #FFF8F8FF.
    public static var ghostWhite: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_GhostWhite()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF8F8FF.
    public static var ghostWhite_: WindowsUI_Color {
        try! Self.ghostWhite
    }

    /// The system-defined color that has an ARGB value of #FFFFD700.
    public static var gold: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Gold()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFD700.
    public static var gold_: WindowsUI_Color {
        try! Self.gold
    }

    /// The system-defined color that has an ARGB value of #FFDAA520.
    public static var goldenrod: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Goldenrod()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFDAA520.
    public static var goldenrod_: WindowsUI_Color {
        try! Self.goldenrod
    }

    /// The system-defined color that has the ARGB value of #FF808080.
    public static var gray: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Gray()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FF808080.
    public static var gray_: WindowsUI_Color {
        try! Self.gray
    }

    /// The system-defined color that has the ARGB value of #FF008000.
    public static var green: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Green()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FF008000.
    public static var green_: WindowsUI_Color {
        try! Self.green
    }

    /// The system-defined color that has an ARGB value of #FFADFF2F.
    public static var greenYellow: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_GreenYellow()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFADFF2F.
    public static var greenYellow_: WindowsUI_Color {
        try! Self.greenYellow
    }

    /// The system-defined color that has an ARGB value of #FFF0FFF0.
    public static var honeydew: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Honeydew()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF0FFF0.
    public static var honeydew_: WindowsUI_Color {
        try! Self.honeydew
    }

    /// The system-defined color that has an ARGB value of #FFFF69B4.
    public static var hotPink: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_HotPink()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFF69B4.
    public static var hotPink_: WindowsUI_Color {
        try! Self.hotPink
    }

    /// The system-defined color that has an ARGB value of #FFCD5C5C.
    public static var indianRed: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_IndianRed()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFCD5C5C.
    public static var indianRed_: WindowsUI_Color {
        try! Self.indianRed
    }

    /// The system-defined color that has an ARGB value of #FF4B0082.
    public static var indigo: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Indigo()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF4B0082.
    public static var indigo_: WindowsUI_Color {
        try! Self.indigo
    }

    /// The system-defined color that has an ARGB value of #FFFFFFF0.
    public static var ivory: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Ivory()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFFFF0.
    public static var ivory_: WindowsUI_Color {
        try! Self.ivory
    }

    /// The system-defined color that has an ARGB value of #FFF0E68C.
    public static var khaki: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Khaki()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF0E68C.
    public static var khaki_: WindowsUI_Color {
        try! Self.khaki
    }

    /// The system-defined color that has an ARGB value of #FFE6E6FA.
    public static var lavender: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Lavender()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFE6E6FA.
    public static var lavender_: WindowsUI_Color {
        try! Self.lavender
    }

    /// The system-defined color that has an ARGB value of #FFFFF0F5.
    public static var lavenderBlush: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LavenderBlush()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFF0F5.
    public static var lavenderBlush_: WindowsUI_Color {
        try! Self.lavenderBlush
    }

    /// The system-defined color that has an ARGB value of #FF7CFC00.
    public static var lawnGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LawnGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF7CFC00.
    public static var lawnGreen_: WindowsUI_Color {
        try! Self.lawnGreen
    }

    /// The system-defined color that has an ARGB value of #FFFFFACD.
    public static var lemonChiffon: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LemonChiffon()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFFACD.
    public static var lemonChiffon_: WindowsUI_Color {
        try! Self.lemonChiffon
    }

    /// The system-defined color that has an ARGB value of #FFADD8E6.
    public static var lightBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFADD8E6.
    public static var lightBlue_: WindowsUI_Color {
        try! Self.lightBlue
    }

    /// The system-defined color that has an ARGB value of #FFF08080.
    public static var lightCoral: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightCoral()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF08080.
    public static var lightCoral_: WindowsUI_Color {
        try! Self.lightCoral
    }

    /// The system-defined color that has an ARGB value of #FFE0FFFF.
    public static var lightCyan: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightCyan()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFE0FFFF.
    public static var lightCyan_: WindowsUI_Color {
        try! Self.lightCyan
    }

    /// The system-defined color that has an ARGB value of #FFFAFAD2.
    public static var lightGoldenrodYellow: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightGoldenrodYellow()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFAFAD2.
    public static var lightGoldenrodYellow_: WindowsUI_Color {
        try! Self.lightGoldenrodYellow
    }

    /// The system-defined color that has the ARGB value of #FFD3D3D3.
    public static var lightGray: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightGray()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFD3D3D3.
    public static var lightGray_: WindowsUI_Color {
        try! Self.lightGray
    }

    /// The system-defined color that has an ARGB value of #FF90EE90.
    public static var lightGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF90EE90.
    public static var lightGreen_: WindowsUI_Color {
        try! Self.lightGreen
    }

    /// The system-defined color that has an ARGB value of #FFFFB6C1.
    public static var lightPink: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightPink()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFB6C1.
    public static var lightPink_: WindowsUI_Color {
        try! Self.lightPink
    }

    /// The system-defined color that has an ARGB value of #FFFFA07A.
    public static var lightSalmon: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightSalmon()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFA07A.
    public static var lightSalmon_: WindowsUI_Color {
        try! Self.lightSalmon
    }

    /// The system-defined color that has an ARGB value of #FF20B2AA.
    public static var lightSeaGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightSeaGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF20B2AA.
    public static var lightSeaGreen_: WindowsUI_Color {
        try! Self.lightSeaGreen
    }

    /// The system-defined color that has an ARGB value of #FF87CEFA.
    public static var lightSkyBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightSkyBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF87CEFA.
    public static var lightSkyBlue_: WindowsUI_Color {
        try! Self.lightSkyBlue
    }

    /// The system-defined color that has an ARGB value of #FF778899.
    public static var lightSlateGray: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightSlateGray()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF778899.
    public static var lightSlateGray_: WindowsUI_Color {
        try! Self.lightSlateGray
    }

    /// The system-defined color that has an ARGB value of #FFB0C4DE.
    public static var lightSteelBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightSteelBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFB0C4DE.
    public static var lightSteelBlue_: WindowsUI_Color {
        try! Self.lightSteelBlue
    }

    /// The system-defined color that has an ARGB value of #FFFFFFE0.
    public static var lightYellow: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LightYellow()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFFFE0.
    public static var lightYellow_: WindowsUI_Color {
        try! Self.lightYellow
    }

    /// The system-defined color that has an ARGB value of #FF00FF00.
    public static var lime: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Lime()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF00FF00.
    public static var lime_: WindowsUI_Color {
        try! Self.lime
    }

    /// The system-defined color that has an ARGB value of #FF32CD32.
    public static var limeGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_LimeGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF32CD32.
    public static var limeGreen_: WindowsUI_Color {
        try! Self.limeGreen
    }

    /// The system-defined color that has an ARGB value of #FFFAF0E6.
    public static var linen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Linen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFAF0E6.
    public static var linen_: WindowsUI_Color {
        try! Self.linen
    }

    /// The system-defined color that has the ARGB value of #FFFF00FF.
    public static var magenta: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Magenta()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFFF00FF.
    public static var magenta_: WindowsUI_Color {
        try! Self.magenta
    }

    /// The system-defined color that has an ARGB value of #FF800000.
    public static var maroon: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Maroon()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF800000.
    public static var maroon_: WindowsUI_Color {
        try! Self.maroon
    }

    /// The system-defined color that has an ARGB value of #FF66CDAA.
    public static var mediumAquamarine: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumAquamarine()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF66CDAA.
    public static var mediumAquamarine_: WindowsUI_Color {
        try! Self.mediumAquamarine
    }

    /// The system-defined color that has an ARGB value of #FF0000CD.
    public static var mediumBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF0000CD.
    public static var mediumBlue_: WindowsUI_Color {
        try! Self.mediumBlue
    }

    /// The system-defined color that has an ARGB value of #FFBA55D3.
    public static var mediumOrchid: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumOrchid()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFBA55D3.
    public static var mediumOrchid_: WindowsUI_Color {
        try! Self.mediumOrchid
    }

    /// The system-defined color that has an ARGB value of #FF9370DB.
    public static var mediumPurple: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumPurple()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF9370DB.
    public static var mediumPurple_: WindowsUI_Color {
        try! Self.mediumPurple
    }

    /// The system-defined color that has an ARGB value of #FF3CB371.
    public static var mediumSeaGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumSeaGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF3CB371.
    public static var mediumSeaGreen_: WindowsUI_Color {
        try! Self.mediumSeaGreen
    }

    /// The system-defined color that has an ARGB value of #FF7B68EE.
    public static var mediumSlateBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumSlateBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF7B68EE.
    public static var mediumSlateBlue_: WindowsUI_Color {
        try! Self.mediumSlateBlue
    }

    /// The system-defined color that has an ARGB value of #FF00FA9A.
    public static var mediumSpringGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumSpringGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF00FA9A.
    public static var mediumSpringGreen_: WindowsUI_Color {
        try! Self.mediumSpringGreen
    }

    /// The system-defined color that has an ARGB value of #FF48D1CC.
    public static var mediumTurquoise: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumTurquoise()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF48D1CC.
    public static var mediumTurquoise_: WindowsUI_Color {
        try! Self.mediumTurquoise
    }

    /// The system-defined color that has an ARGB value of #FFC71585.
    public static var mediumVioletRed: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MediumVioletRed()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFC71585.
    public static var mediumVioletRed_: WindowsUI_Color {
        try! Self.mediumVioletRed
    }

    /// The system-defined color that has an ARGB value of #FF191970.
    public static var midnightBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MidnightBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF191970.
    public static var midnightBlue_: WindowsUI_Color {
        try! Self.midnightBlue
    }

    /// The system-defined color that has an ARGB value of #FFF5FFFA.
    public static var mintCream: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MintCream()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF5FFFA.
    public static var mintCream_: WindowsUI_Color {
        try! Self.mintCream
    }

    /// The system-defined color that has an ARGB value of #FFFFE4E1.
    public static var mistyRose: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_MistyRose()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFE4E1.
    public static var mistyRose_: WindowsUI_Color {
        try! Self.mistyRose
    }

    /// The system-defined color that has an ARGB value of #FFFFE4B5.
    public static var moccasin: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Moccasin()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFE4B5.
    public static var moccasin_: WindowsUI_Color {
        try! Self.moccasin
    }

    /// The system-defined color that has an ARGB value of #FFFFDEAD.
    public static var navajoWhite: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_NavajoWhite()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFDEAD.
    public static var navajoWhite_: WindowsUI_Color {
        try! Self.navajoWhite
    }

    /// The system-defined color that has an ARGB value of #FF000080.
    public static var navy: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Navy()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF000080.
    public static var navy_: WindowsUI_Color {
        try! Self.navy
    }

    /// The system-defined color that has an ARGB value of #FFFDF5E6.
    public static var oldLace: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_OldLace()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFDF5E6.
    public static var oldLace_: WindowsUI_Color {
        try! Self.oldLace
    }

    /// The system-defined color that has an ARGB value of #FF808000.
    public static var olive: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Olive()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF808000.
    public static var olive_: WindowsUI_Color {
        try! Self.olive
    }

    /// The system-defined color that has an ARGB value of #FF6B8E23.
    public static var oliveDrab: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_OliveDrab()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF6B8E23.
    public static var oliveDrab_: WindowsUI_Color {
        try! Self.oliveDrab
    }

    /// The system-defined color that has the ARGB value of #FFFFA500.
    public static var orange: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Orange()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFFFA500.
    public static var orange_: WindowsUI_Color {
        try! Self.orange
    }

    /// The system-defined color that has an ARGB value of #FFFF4500.
    public static var orangeRed: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_OrangeRed()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFF4500.
    public static var orangeRed_: WindowsUI_Color {
        try! Self.orangeRed
    }

    /// The system-defined color that has an ARGB value of #FFDA70D6.
    public static var orchid: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Orchid()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFDA70D6.
    public static var orchid_: WindowsUI_Color {
        try! Self.orchid
    }

    /// The system-defined color that has an ARGB value of #FFEEE8AA.
    public static var paleGoldenrod: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_PaleGoldenrod()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFEEE8AA.
    public static var paleGoldenrod_: WindowsUI_Color {
        try! Self.paleGoldenrod
    }

    /// The system-defined color that has an ARGB value of #FF98FB98.
    public static var paleGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_PaleGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF98FB98.
    public static var paleGreen_: WindowsUI_Color {
        try! Self.paleGreen
    }

    /// The system-defined color that has an ARGB value of #FFAFEEEE.
    public static var paleTurquoise: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_PaleTurquoise()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFAFEEEE.
    public static var paleTurquoise_: WindowsUI_Color {
        try! Self.paleTurquoise
    }

    /// The system-defined color that has an ARGB value of #FFDB7093.
    public static var paleVioletRed: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_PaleVioletRed()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFDB7093.
    public static var paleVioletRed_: WindowsUI_Color {
        try! Self.paleVioletRed
    }

    /// The system-defined color that has an ARGB value of #FFFFEFD5.
    public static var papayaWhip: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_PapayaWhip()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFEFD5.
    public static var papayaWhip_: WindowsUI_Color {
        try! Self.papayaWhip
    }

    /// The system-defined color that has an ARGB value of #FFFFDAB9.
    public static var peachPuff: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_PeachPuff()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFDAB9.
    public static var peachPuff_: WindowsUI_Color {
        try! Self.peachPuff
    }

    /// The system-defined color that has an ARGB value of #FFCD853F.
    public static var peru: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Peru()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFCD853F.
    public static var peru_: WindowsUI_Color {
        try! Self.peru
    }

    /// The system-defined color that has an ARGB value of #FFFFC0CB.
    public static var pink: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Pink()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFC0CB.
    public static var pink_: WindowsUI_Color {
        try! Self.pink
    }

    /// The system-defined color that has an ARGB value of #FFDDA0DD.
    public static var plum: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Plum()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFDDA0DD.
    public static var plum_: WindowsUI_Color {
        try! Self.plum
    }

    /// The system-defined color that has an ARGB value of #FFB0E0E6.
    public static var powderBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_PowderBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFB0E0E6.
    public static var powderBlue_: WindowsUI_Color {
        try! Self.powderBlue
    }

    /// The system-defined color that has the ARGB value of #FF800080.
    public static var purple: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Purple()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FF800080.
    public static var purple_: WindowsUI_Color {
        try! Self.purple
    }

    /// The system-defined color that has the ARGB value of #FFFF0000.
    public static var red: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Red()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFFF0000.
    public static var red_: WindowsUI_Color {
        try! Self.red
    }

    /// The system-defined color that has an ARGB value of #FFBC8F8F.
    public static var rosyBrown: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_RosyBrown()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFBC8F8F.
    public static var rosyBrown_: WindowsUI_Color {
        try! Self.rosyBrown
    }

    /// The system-defined color that has an ARGB value of #FF4169E1.
    public static var royalBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_RoyalBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF4169E1.
    public static var royalBlue_: WindowsUI_Color {
        try! Self.royalBlue
    }

    /// The system-defined color that has an ARGB value of #FF8B4513.
    public static var saddleBrown: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SaddleBrown()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF8B4513.
    public static var saddleBrown_: WindowsUI_Color {
        try! Self.saddleBrown
    }

    /// The system-defined color that has an ARGB value of #FFFA8072.
    public static var salmon: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Salmon()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFA8072.
    public static var salmon_: WindowsUI_Color {
        try! Self.salmon
    }

    /// The system-defined color that has an ARGB value of #FFF4A460.
    public static var sandyBrown: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SandyBrown()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF4A460.
    public static var sandyBrown_: WindowsUI_Color {
        try! Self.sandyBrown
    }

    /// The system-defined color that has an ARGB value of #FF2E8B57.
    public static var seaGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SeaGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF2E8B57.
    public static var seaGreen_: WindowsUI_Color {
        try! Self.seaGreen
    }

    /// The system-defined color that has an ARGB value of #FFFFF5EE.
    public static var seaShell: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SeaShell()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFF5EE.
    public static var seaShell_: WindowsUI_Color {
        try! Self.seaShell
    }

    /// The system-defined color that has an ARGB value of #FFA0522D.
    public static var sienna: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Sienna()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFA0522D.
    public static var sienna_: WindowsUI_Color {
        try! Self.sienna
    }

    /// The system-defined color that has an ARGB value of #FFC0C0C0.
    public static var silver: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Silver()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFC0C0C0.
    public static var silver_: WindowsUI_Color {
        try! Self.silver
    }

    /// The system-defined color that has an ARGB value of #FF87CEEB.
    public static var skyBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SkyBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF87CEEB.
    public static var skyBlue_: WindowsUI_Color {
        try! Self.skyBlue
    }

    /// The system-defined color that has an ARGB value of #FF6A5ACD.
    public static var slateBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SlateBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF6A5ACD.
    public static var slateBlue_: WindowsUI_Color {
        try! Self.slateBlue
    }

    /// The system-defined color that has an ARGB value of #FF708090.
    public static var slateGray: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SlateGray()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF708090.
    public static var slateGray_: WindowsUI_Color {
        try! Self.slateGray
    }

    /// The system-defined color that has an ARGB value of #FFFFFAFA.
    public static var snow: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Snow()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFFFAFA.
    public static var snow_: WindowsUI_Color {
        try! Self.snow
    }

    /// The system-defined color that has an ARGB value of #FF00FF7F.
    public static var springGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SpringGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF00FF7F.
    public static var springGreen_: WindowsUI_Color {
        try! Self.springGreen
    }

    /// The system-defined color that has an ARGB value of #FF4682B4.
    public static var steelBlue: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_SteelBlue()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF4682B4.
    public static var steelBlue_: WindowsUI_Color {
        try! Self.steelBlue
    }

    /// The system-defined color that has an ARGB value of #FFD2B48C.
    public static var tan: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Tan()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFD2B48C.
    public static var tan_: WindowsUI_Color {
        try! Self.tan
    }

    /// The system-defined color that has an ARGB value of #FF008080.
    public static var teal: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Teal()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF008080.
    public static var teal_: WindowsUI_Color {
        try! Self.teal
    }

    /// The system-defined color that has an ARGB value of #FFD8BFD8.
    public static var thistle: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Thistle()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFD8BFD8.
    public static var thistle_: WindowsUI_Color {
        try! Self.thistle
    }

    /// The system-defined color that has an ARGB value of #FFFF6347.
    public static var tomato: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Tomato()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFFF6347.
    public static var tomato_: WindowsUI_Color {
        try! Self.tomato
    }

    /// The system-defined color that has the ARGB value of #00FFFFFF.
    public static var transparent: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Transparent()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #00FFFFFF.
    public static var transparent_: WindowsUI_Color {
        try! Self.transparent
    }

    /// The system-defined color that has an ARGB value of #FF40E0D0.
    public static var turquoise: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Turquoise()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF40E0D0.
    public static var turquoise_: WindowsUI_Color {
        try! Self.turquoise
    }

    /// The system-defined color that has an ARGB value of #FFEE82EE.
    public static var violet: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Violet()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFEE82EE.
    public static var violet_: WindowsUI_Color {
        try! Self.violet
    }

    /// The system-defined color that has an ARGB value of #FFF5DEB3.
    public static var wheat: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Wheat()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF5DEB3.
    public static var wheat_: WindowsUI_Color {
        try! Self.wheat
    }

    /// The system-defined color that has the ARGB value of #FFFFFFFF.
    public static var white: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_White()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFFFFFFF.
    public static var white_: WindowsUI_Color {
        try! Self.white
    }

    /// The system-defined color that has an ARGB value of #FFF5F5F5.
    public static var whiteSmoke: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_WhiteSmoke()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FFF5F5F5.
    public static var whiteSmoke_: WindowsUI_Color {
        try! Self.whiteSmoke
    }

    /// The system-defined color that has the ARGB value of #FFFFFF00.
    public static var yellow: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_Yellow()
        }
    }

    /// Gets the system-defined color that has the ARGB value of #FFFFFF00.
    public static var yellow_: WindowsUI_Color {
        try! Self.yellow
    }

    /// The system-defined color that has an ARGB value of #FF9ACD32.
    public static var yellowGreen: WindowsUI_Color {
        get throws {
            try _icolorsStatics.get_YellowGreen()
        }
    }

    /// Gets the system-defined color that has an ARGB value of #FF9ACD32.
    public static var yellowGreen_: WindowsUI_Color {
        try! Self.yellowGreen
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_MicrosoftUI_IColors>) {
        super.init(_wrapping: consume inner)
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Microsoft.UI.Colors")
            }
        }
    }

    private static var _lazyIColorsStatics: COM.COMReference<SWRT_MicrosoftUI_IColorsStatics>.Optional = .none

    internal static var _icolorsStatics: COM.COMInterop<SWRT_MicrosoftUI_IColorsStatics> {
        get throws {
            try _lazyIColorsStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_MicrosoftUI_IColorsStatics.self)).cast()
            }
        }
    }
}