// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Provides data for the FlyoutBase.Closing event
public final class MicrosoftUIXamlControlsPrimitives_FlyoutBaseClosingEventArgs: WindowsRuntime.WinRTImport<MicrosoftUIXamlControlsPrimitives_FlyoutBaseClosingEventArgsBinding>, @unchecked Sendable {
    /// true to prevent the flyout from closing; otherwise, false.
    public var cancel: Swift.Bool {
        get throws {
            try _interop.get_Cancel()
        }
    }

    /// Sets a value that indicates whether the flyout should be prevented from closing.
    /// - Parameter newValue: true to prevent the flyout from closing; otherwise, false.
    public func cancel(_ value: Swift.Bool) throws {
        try _interop.put_Cancel(value)
    }

    /// Gets or sets a value that indicates whether the flyout should be prevented from closing.
    public var cancel_: Swift.Bool {
        get {
            try! self.cancel
        }
        set {
            try! self.cancel(newValue)
        }
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_MicrosoftUIXamlControlsPrimitives_IFlyoutBaseClosingEventArgs>) {
        super.init(_wrapping: consume inner)
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Microsoft.UI.Xaml.Controls.Primitives.FlyoutBaseClosingEventArgs")
            }
        }
    }
}