// Generated by swift-winrt
// swiftlint:disable all

import UWP

public typealias FontStretch = WindowsUIText_FontStretch
public typealias FontStyle = WindowsUIText_FontStyle
public typealias FontWeight = WindowsUIText_FontWeight
public typealias TextDecorations = WindowsUIText_TextDecorations