// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Provides values that can be used for decoding operations to optimize for logical versus physical pixels in the source image file.
public struct MicrosoftUIXamlMediaImaging_DecodePixelType: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Use a physical pixel value.
    public static let physical = Self()

    /// Use a logical pixel value.
    public static let logical = Self(rawValue: 1)
}