// Generated by swift-winrt
// swiftlint:disable all

import UWP

public typealias IPointerPointTransform = WindowsUIInput_IPointerPointTransform

public protocol IPointerPointTransformProtocol: WindowsUIInput_IPointerPointTransformProtocol {
}

public typealias IPointerPointTransformBinding = WindowsUIInput_IPointerPointTransformBinding
public typealias PointerPoint = WindowsUIInput_PointerPoint
public typealias PointerPointProperties = WindowsUIInput_PointerPointProperties
public typealias PointerUpdateKind = WindowsUIInput_PointerUpdateKind