// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// This represents an IDXGISurface and can be used to interop between Windows Runtime components that need to exchange **IDXGISurface** references.
public typealias WindowsGraphicsDirectXDirect3D11_IDirect3DSurface = any WindowsGraphicsDirectXDirect3D11_IDirect3DSurfaceProtocol


/// This represents an IDXGISurface and can be used to interop between Windows Runtime components that need to exchange **IDXGISurface** references.
public protocol WindowsGraphicsDirectXDirect3D11_IDirect3DSurfaceProtocol: WindowsFoundation_IClosableProtocol {
    /// A Direct3DSurfaceDescription describing the surface.
    var description: WindowsGraphicsDirectXDirect3D11_Direct3DSurfaceDescription { get throws }
}

extension WindowsGraphicsDirectXDirect3D11_IDirect3DSurfaceProtocol {
    /// Gets a Direct3DSurfaceDescription describing the surface.
    public var description_: WindowsGraphicsDirectXDirect3D11_Direct3DSurfaceDescription {
        try! self.description
    }
}