// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlMedia_TransformBinding: WindowsRuntime.ComposableClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlMedia_Transform
    public typealias ABIStruct = SWRT_MicrosoftUIXamlMedia_ITransform

    public static let typeName = "Microsoft.UI.Xaml.Media.Transform"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlMedia_Transform(_wrapping: consume reference)
    }
}