// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP


/// Specifies the rounding methods used for converting screen coordinates (float to integer).
public struct MicrosoftUIContent_ContentCoordinateRoundingMode: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Use the current floating-point unit (FPU) setting. Default.
    public static let auto = Self()

    /// Rounds down to the largest integer less than or equal to the provided floating point number.
    public static let floor = Self(rawValue: 1)

    /// Rounds up or down, depending on the value of the provided floating point number.
    public static let round = Self(rawValue: 2)

    /// Rounds up to the smallest integer greater than or equal to the provided floating point number.
    public static let ceiling = Self(rawValue: 3)
}