// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftWindowsApplicationModelResources_ResourceManagerBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftWindowsApplicationModelResources_ResourceManager
    public typealias ABIStruct = SWRT_MicrosoftWindowsApplicationModelResources_IResourceManager

    public static let typeName = "Microsoft.Windows.ApplicationModel.Resources.ResourceManager"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftWindowsApplicationModelResources_ResourceManager(_wrapping: consume reference)
    }
}