// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftWindowsApplicationModelResources_ResourceMapBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftWindowsApplicationModelResources_ResourceMap
    public typealias ABIStruct = SWRT_MicrosoftWindowsApplicationModelResources_IResourceMap

    public static let typeName = "Microsoft.Windows.ApplicationModel.Resources.ResourceMap"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftWindowsApplicationModelResources_ResourceMap(_wrapping: consume reference)
    }
}