// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Base class for composition animations.
public typealias WindowsUIComposition_ICompositionAnimationBase = any WindowsUIComposition_ICompositionAnimationBaseProtocol


/// Base class for composition animations.
public protocol WindowsUIComposition_ICompositionAnimationBaseProtocol: IInspectableProtocol {
}