// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Represents an object that casts a projected shadow.
public final class WindowsUIComposition_CompositionProjectedShadowCaster: WindowsUIComposition_CompositionObject, @unchecked Sendable {
    /// The brush used to draw the shadow.
    public var brush: WindowsUIComposition_CompositionBrush {
        get throws {
            try COM.NullResult.unwrap(_icompositionProjectedShadowCaster.get_Brush())
        }
    }

    /// Sets the brush used to draw the shadow.
    /// - Parameter newValue: The brush used to draw the shadow.
    public func brush(_ value: WindowsUIComposition_CompositionBrush?) throws {
        try _icompositionProjectedShadowCaster.put_Brush(value)
    }

    /// Gets or sets the brush used to draw the shadow.
    public var brush_: WindowsUIComposition_CompositionBrush! {
        get {
            try! NullResult.catch(self.brush)
        }
        set {
            try! self.brush(newValue)
        }
    }

    /// The Visual that casts the shadow.
    public var castingVisual: WindowsUIComposition_Visual {
        get throws {
            try COM.NullResult.unwrap(_icompositionProjectedShadowCaster.get_CastingVisual())
        }
    }

    /// Sets the Visual that casts the shadow.
    /// - Parameter newValue: The Visual that casts the shadow.
    public func castingVisual(_ value: WindowsUIComposition_Visual?) throws {
        try _icompositionProjectedShadowCaster.put_CastingVisual(value)
    }

    /// Gets or sets the Visual that casts the shadow.
    public var castingVisual_: WindowsUIComposition_Visual! {
        get {
            try! NullResult.catch(self.castingVisual)
        }
        set {
            try! self.castingVisual(newValue)
        }
    }

    // MARK: Implementation details

    public init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsUIComposition_ICompositionProjectedShadowCaster>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    private var _lazyICompositionProjectedShadowCaster: COM.COMReference<SWRT_WindowsUIComposition_ICompositionProjectedShadowCaster>.Optional = .none

    internal var _icompositionProjectedShadowCaster: COM.COMInterop<SWRT_WindowsUIComposition_ICompositionProjectedShadowCaster> {
        get throws {
            try _lazyICompositionProjectedShadowCaster.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUIComposition_ICompositionProjectedShadowCaster.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.UI.Composition.CompositionProjectedShadowCaster")
            }
        }
    }
}