// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// A ContainerVisual whose children are flattened into a single layer.
public final class WindowsUIComposition_LayerVisual: WindowsUIComposition_ContainerVisual, @unchecked Sendable {
    /// The effect to be applied to the flattened representation of the children of a LayerVisual.
    public var effect: WindowsUIComposition_CompositionEffectBrush {
        get throws {
            try COM.NullResult.unwrap(_ilayerVisual.get_Effect())
        }
    }

    /// The effect to be applied to the flattened representation of the children of a LayerVisual.
    /// - Parameter newValue: The effect to be applied to the flattened representation of the children of a LayerVisual.
    public func effect(_ value: WindowsUIComposition_CompositionEffectBrush?) throws {
        try _ilayerVisual.put_Effect(value)
    }

    /// The effect to be applied to the flattened representation of the children of a LayerVisual.
    public var effect_: WindowsUIComposition_CompositionEffectBrush! {
        get {
            try! NullResult.catch(self.effect)
        }
        set {
            try! self.effect(newValue)
        }
    }


    ///       
    public var shadow: WindowsUIComposition_CompositionShadow {
        get throws {
            try COM.NullResult.unwrap(_ilayerVisual2.get_Shadow())
        }
    }

    /// The shadow to be applied to the flattened representation of the children of a LayerVisual.
    /// - Parameter newValue: 
    ///       
    public func shadow(_ value: WindowsUIComposition_CompositionShadow?) throws {
        try _ilayerVisual2.put_Shadow(value)
    }

    /// The shadow to be applied to the flattened representation of the children of a LayerVisual.
    public var shadow_: WindowsUIComposition_CompositionShadow! {
        get {
            try! NullResult.catch(self.shadow)
        }
        set {
            try! self.shadow(newValue)
        }
    }

    // MARK: Implementation details

    public init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsUIComposition_ILayerVisual>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    private var _lazyILayerVisual: COM.COMReference<SWRT_WindowsUIComposition_ILayerVisual>.Optional = .none

    internal var _ilayerVisual: COM.COMInterop<SWRT_WindowsUIComposition_ILayerVisual> {
        get throws {
            try _lazyILayerVisual.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUIComposition_ILayerVisual.self)).cast()
            }
        }
    }

    private var _lazyILayerVisual2: COM.COMReference<SWRT_WindowsUIComposition_ILayerVisual2>.Optional = .none

    internal var _ilayerVisual2: COM.COMInterop<SWRT_WindowsUIComposition_ILayerVisual2> {
        get throws {
            try _lazyILayerVisual2.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUIComposition_ILayerVisual2.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.UI.Composition.LayerVisual")
            }
        }
    }
}