// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Represents a linear function for interpolating between animation key frames.
public final class WindowsUIComposition_LinearEasingFunction: WindowsUIComposition_CompositionEasingFunction, @unchecked Sendable {
    // MARK: Implementation details

    public init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsUIComposition_ILinearEasingFunction>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    private var _lazyILinearEasingFunction: COM.COMReference<SWRT_WindowsUIComposition_ILinearEasingFunction>.Optional = .none

    internal var _ilinearEasingFunction: COM.COMInterop<SWRT_WindowsUIComposition_ILinearEasingFunction> {
        get throws {
            try _lazyILinearEasingFunction.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsUIComposition_ILinearEasingFunction.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.UI.Composition.LinearEasingFunction")
            }
        }
    }
}