// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

/// Represents the method that handles the KeyUp and KeyDown events.
/// - Parameter sender: The object where the event handler is attached.
/// - Parameter e: The event data.
public typealias MicrosoftUIXamlInput_KeyEventHandler = (WindowsRuntime.IInspectable?, MicrosoftUIXamlInput_KeyRoutedEventArgs?) throws -> Swift.Void