// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

/// Represents the method that will handle ManipulationDelta and related events.
/// - Parameter sender: The object where the handler is attached.
/// - Parameter e: Event data for the event.
public typealias MicrosoftUIXamlInput_ManipulationDeltaEventHandler = (WindowsRuntime.IInspectable?, MicrosoftUIXamlInput_ManipulationDeltaRoutedEventArgs?) throws -> Swift.Void