// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Provides info about a tile notification that was displayed in the **Start** menu.
public final class WindowsUINotifications_ShownTileNotification: WindowsRuntime.WinRTImport<WindowsUINotifications_ShownTileNotificationBinding>, @unchecked Sendable {
    /// The arguments from the notification’s XML payload for the tile size that was displayed, or an empty string if there were no arguments provided for that size.
    public var arguments: Swift.String {
        get throws {
            try _interop.get_Arguments()
        }
    }

    /// Gets the arguments from the notification’s XML payload for the tile size that was displayed, or an empty string if there were no arguments provided for that size.
    public var arguments_: Swift.String {
        try! self.arguments
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsUINotifications_IShownTileNotification>) {
        super.init(_wrapping: consume inner)
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.UI.Notifications.ShownTileNotification")
            }
        }
    }
}