// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Specifies a mapping on a per-assembly basis between a XAML namespace and a library-code namespace for backing types, which is then used for type resolution by a XAML object writer or XAML schema context.
public struct MicrosoftUIXamlMarkup_XmlnsDefinition: Codable, Hashable, Sendable {
    /// The XAML namespace identifier specified in the attribute.
    public var xmlNamespace: Swift.String

    /// The library-code namespace, specified as a string.
    public var namespace: Swift.String

    public init() {
        self.xmlNamespace = ""
        self.namespace = ""
    }

    public init(xmlNamespace: Swift.String, namespace: Swift.String) {
        self.xmlNamespace = xmlNamespace
        self.namespace = namespace
    }
}