// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsStorageFileProperties_StorageItemContentPropertiesBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = WindowsStorageFileProperties_StorageItemContentProperties
    public typealias ABIStruct = SWRT_WindowsStorageFileProperties_IStorageItemContentProperties

    public static let typeName = "Windows.Storage.FileProperties.StorageItemContentProperties"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsStorageFileProperties_StorageItemContentProperties(_wrapping: consume reference)
    }
}