// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlInput_ManipulationCompletedRoutedEventArgsBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlInput_ManipulationCompletedRoutedEventArgs
    public typealias ABIStruct = SWRT_MicrosoftUIXamlInput_IManipulationCompletedRoutedEventArgs

    public static let typeName = "Microsoft.UI.Xaml.Input.ManipulationCompletedRoutedEventArgs"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlInput_ManipulationCompletedRoutedEventArgs(_wrapping: consume reference)
    }
}