// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlInput_ManipulationStartingRoutedEventArgsBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlInput_ManipulationStartingRoutedEventArgs
    public typealias ABIStruct = SWRT_MicrosoftUIXamlInput_IManipulationStartingRoutedEventArgs

    public static let typeName = "Microsoft.UI.Xaml.Input.ManipulationStartingRoutedEventArgs"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlInput_ManipulationStartingRoutedEventArgs(_wrapping: consume reference)
    }
}