// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlInput_PointerBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlInput_Pointer
    public typealias ABIStruct = SWRT_MicrosoftUIXamlInput_IPointer

    public static let typeName = "Microsoft.UI.Xaml.Input.Pointer"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlInput_Pointer(_wrapping: consume reference)
    }
}