// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXamlInput_InertiaTranslationBehaviorBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXamlInput_InertiaTranslationBehavior
    public typealias ABIStruct = SWRT_MicrosoftUIXamlInput_IInertiaTranslationBehavior

    public static let typeName = "Microsoft.UI.Xaml.Input.InertiaTranslationBehavior"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXamlInput_InertiaTranslationBehavior(_wrapping: consume reference)
    }
}