// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

extension MicrosoftUIXamlAutomationPeers_AutomationEvents: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Microsoft.UI.Xaml.Automation.Peers.AutomationEvents"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x9013C9AF, 0x76C3, 0x5138, 0x9B8A, 0x8477E2CD252C)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xD5B555AA, 0x67AC, 0x5B8E, 0xBC0C, 0x22762D744BBC)
    }
}