// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP


/// Represents an object that your app can use to defer a DispatcherQueue from exiting.
public final class MicrosoftUIDispatching_DispatcherExitDeferral: WindowsRuntime.WinRTImport<MicrosoftUIDispatching_DispatcherExitDeferralBinding>, @unchecked Sendable {
    /// Creates a new instance of DispatcherExitDeferral.
    public init() throws {
        let _instance = COM.COMReference(transferringRef: try Self._iactivationFactory.activateInstance(binding: MicrosoftUIDispatching_DispatcherExitDeferralBinding.self))
        super.init(_wrapping: consume _instance)
    }

    /// Called by your app to notify that it has finished processing the notification, and the DispatcherQueue can now exit.
    public func complete() throws {
        try _interop.complete()
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_MicrosoftUIDispatching_IDispatcherExitDeferral>) {
        super.init(_wrapping: consume inner)
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Microsoft.UI.Dispatching.DispatcherExitDeferral")
            }
        }
    }
}