// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsUIComposition_CompositionShapeBinding: WindowsRuntime.ComposableClassBinding {
    public typealias SwiftObject = WindowsUIComposition_CompositionShape
    public typealias ABIStruct = SWRT_WindowsUIComposition_ICompositionShape

    public static let typeName = "Windows.UI.Composition.CompositionShape"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsUIComposition_CompositionShape(_wrapping: consume reference)
    }
}