// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

extension WindowsUIComposition_CompositionDropShadowSourcePolicy: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Windows.UI.Composition.CompositionDropShadowSourcePolicy"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x0C2A5390, 0x9FF7, 0x5C9D, 0xA24D, 0x889362EF1F92)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x9C890EB1, 0xD9FE, 0x59C3, 0x8DAE, 0x86579A3A982C)
    }
}