// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsUIComposition_CompositionRectangleGeometryBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = WindowsUIComposition_CompositionRectangleGeometry
    public typealias ABIStruct = SWRT_WindowsUIComposition_ICompositionRectangleGeometry

    public static let typeName = "Windows.UI.Composition.CompositionRectangleGeometry"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsUIComposition_CompositionRectangleGeometry(_wrapping: consume reference)
    }
}