// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsUIComposition_CompositionEffectFactoryBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = WindowsUIComposition_CompositionEffectFactory
    public typealias ABIStruct = SWRT_WindowsUIComposition_ICompositionEffectFactory

    public static let typeName = "Windows.UI.Composition.CompositionEffectFactory"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsUIComposition_CompositionEffectFactory(_wrapping: consume reference)
    }
}