// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

extension WindowsUIComposition_CompositionCompositeMode: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Windows.UI.Composition.CompositionCompositeMode"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x057016B8, 0xD107, 0x5055, 0xB43C, 0x2E4C47E91699)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xD3AD5D7E, 0x213F, 0x5F23, 0x94E3, 0x22B84525D31F)
    }
}