// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

extension WindowsUIComposition_CompositionStretch: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Windows.UI.Composition.CompositionStretch"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x28A16604, 0xBF10, 0x5D48, 0x98F1, 0x3D4B221E2DE2)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x6198B0D4, 0xFD0A, 0x5528, 0x818B, 0x7191F84CB9E2)
    }
}