// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public enum WindowsUIComposition_ICompositionSurfaceBinding: WindowsRuntime.InterfaceBinding {
    public typealias SwiftObject = WindowsUIComposition_ICompositionSurface
    public typealias ABIStruct = SWRT_WindowsUIComposition_ICompositionSurface

    public static let typeName = "Windows.UI.Composition.ICompositionSurface"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        Import(_wrapping: consume reference)
    }

    private final class Import: WinRTImport<WindowsUIComposition_ICompositionSurfaceBinding>, WindowsUIComposition_ICompositionSurfaceProtocol {
    }

    public static var virtualTablePointer: UnsafeRawPointer {
        .init(withUnsafePointer(to: &virtualTable) { $0 })
    }

    private static var virtualTable = SWRT_WindowsUIComposition_ICompositionSurface_VirtualTable(
        QueryInterface: { IUnknownVirtualTable.QueryInterface($0, $1, $2) },
        AddRef: { IUnknownVirtualTable.AddRef($0) },
        Release: { IUnknownVirtualTable.Release($0) },
        GetIids: { IInspectableVirtualTable.GetIids($0, $1, $2) },
        GetRuntimeClassName: { IInspectableVirtualTable.GetRuntimeClassName($0, $1) },
        GetTrustLevel: { IInspectableVirtualTable.GetTrustLevel($0, $1) }
    )
}