// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXaml_ApplicationInitializationCallbackParamsBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXaml_ApplicationInitializationCallbackParams
    public typealias ABIStruct = SWRT_MicrosoftUIXaml_IApplicationInitializationCallbackParams

    public static let typeName = "Microsoft.UI.Xaml.ApplicationInitializationCallbackParams"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXaml_ApplicationInitializationCallbackParams(_wrapping: consume reference)
    }
}