// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXaml_XamlResourceReferenceFailedEventArgsBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXaml_XamlResourceReferenceFailedEventArgs
    public typealias ABIStruct = SWRT_MicrosoftUIXaml_IXamlResourceReferenceFailedEventArgs

    public static let typeName = "Microsoft.UI.Xaml.XamlResourceReferenceFailedEventArgs"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXaml_XamlResourceReferenceFailedEventArgs(_wrapping: consume reference)
    }
}