// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public enum MicrosoftUIXaml_CreateDefaultValueCallbackBinding: WindowsRuntime.DelegateBinding {
    public typealias SwiftObject = MicrosoftUIXaml_CreateDefaultValueCallback
    public typealias ABIStruct = SWRT_MicrosoftUIXaml_CreateDefaultValueCallback

    public static let typeName = "Microsoft.UI.Xaml.ICreateDefaultValueCallback"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x76743E58, 0x38DF, 0x5D40, 0xB419, 0xFC73330B222F)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xAF2BBA6F, 0x78F5, 0x58D6, 0x8AF1, 0xB5BBFD569CA0)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        Import(_wrapping: consume reference).invoke
    }

    public static func toCOM(_ object: @escaping SwiftObject) throws -> ABIReference {
        ExportedDelegate<Self>(object).toCOM()
    }

    private final class Import: COMImport<MicrosoftUIXaml_CreateDefaultValueCallbackBinding> {
        public func invoke() throws -> WindowsRuntime.IInspectable {
            try COM.NullResult.unwrap(_interop.invoke())
        }
    }

    public static var virtualTablePointer: UnsafeRawPointer {
        .init(withUnsafePointer(to: &virtualTable) { $0 })
    }

    private static var virtualTable = SWRT_MicrosoftUIXaml_CreateDefaultValueCallback_VirtualTable(
        QueryInterface: { IUnknownVirtualTable.QueryInterface($0, $1, $2) },
        AddRef: { IUnknownVirtualTable.AddRef($0) },
        Release: { IUnknownVirtualTable.Release($0) },
        Invoke: { this, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let _result_swift = try COM.NullResult.`catch`(try this())
            _result.pointee = try WindowsRuntime.IInspectableBinding.toABI(_result_swift)
        } }
    )
}