// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

extension MicrosoftUIXaml_DispatcherShutdownMode: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Microsoft.UI.Xaml.DispatcherShutdownMode"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x12B4FACC, 0x69F3, 0x55DA, 0x921D, 0xC2474C256347)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x24948D06, 0xE00D, 0x5E1B, 0xBB07, 0xD1B8D17EC343)
    }
}