// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

extension MicrosoftUIXaml_HorizontalAlignment: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "Microsoft.UI.Xaml.HorizontalAlignment"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x9A9AC1C4, 0x5B84, 0x53A0, 0x894A, 0x9062FF232F5B)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xC345AEA3, 0x765E, 0x5F30, 0xBA56, 0x0537958F2CEF)
    }
}