// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

public class MicrosoftUIXaml_DragUIOverrideBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIXaml_DragUIOverride
    public typealias ABIStruct = SWRT_MicrosoftUIXaml_IDragUIOverride

    public static let typeName = "Microsoft.UI.Xaml.DragUIOverride"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIXaml_DragUIOverride(_wrapping: consume reference)
    }
}