// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Represents the thumbnail image associated with a system resource (like a file or folder).
public final class WindowsStorageFileProperties_StorageItemThumbnail: WindowsRuntime.WinRTImport<WindowsStorageFileProperties_StorageItemThumbnailBinding>, WindowsStorageStreams_IRandomAccessStreamWithContentTypeProtocol, WindowsStorageStreams_IContentTypeProviderProtocol, WindowsStorageStreams_IRandomAccessStreamProtocol, WindowsStorageStreams_IOutputStreamProtocol, WindowsFoundation_IClosableProtocol, WindowsStorageStreams_IInputStreamProtocol {
    // MARK: Windows.Storage.Streams.IContentTypeProvider members

    /// The MIME content type.
    public var contentType: Swift.String {
        get throws {
            try _icontentTypeProvider.get_ContentType()
        }
    }

    // MARK: Windows.Storage.Streams.IRandomAccessStream members

    /// Retrieves the thumbnail image data as an undecoded stream.
    /// - Parameter position: The position in the storage item to start reading thumbnail image data.
    /// - Returns: An object for reading the thumbnail image data.
    public func getInputStreamAt(_ position: Swift.UInt64) throws -> WindowsStorageStreams_IInputStream {
        try COM.NullResult.unwrap(_irandomAccessStream.getInputStreamAt(position))
    }

    /// Retrieves an output stream object for writing thumbnail image data to a storage item.
    /// - Parameter position: The position in the storage item to start writing thumbnail image data.
    /// - Returns: The output stream.
    public func getOutputStreamAt(_ position: Swift.UInt64) throws -> WindowsStorageStreams_IOutputStream {
        try COM.NullResult.unwrap(_irandomAccessStream.getOutputStreamAt(position))
    }

    /// Sets the offset of the thumbnail stream to the specified value.
    /// - Parameter position: The number of bytes from the start of the thumbnail stream where the position of the thumbnail stream is set.
    public func seek(_ position: Swift.UInt64) throws {
        try _irandomAccessStream.seek(position)
    }

    /// Creates a new stream over the thumbnail that is represented by the current storageItemThumbnail object.
    /// - Returns: The new thumbnail stream. The initial, internal position of the stream is 0.
    public func cloneStream() throws -> WindowsStorageStreams_IRandomAccessStream {
        try COM.NullResult.unwrap(_irandomAccessStream.cloneStream())
    }

    /// True if the thumbnail stream can be read from. Otherwise, false.
    public var canRead: Swift.Bool {
        get throws {
            try _irandomAccessStream.get_CanRead()
        }
    }

    /// True if the thumbnail stream can be written to. Otherwise, false.
    public var canWrite: Swift.Bool {
        get throws {
            try _irandomAccessStream.get_CanWrite()
        }
    }

    /// The number of bytes from the start of the thumbnail stream.
    public var position: Swift.UInt64 {
        get throws {
            try _irandomAccessStream.get_Position()
        }
    }

    /// The size, in bytes, of the thumbnail image.
    public var size: Swift.UInt64 {
        get throws {
            try _irandomAccessStream.get_Size()
        }
    }

    /// Sets the size of the thumbnail image.
    /// - Parameter newValue: The size, in bytes, of the thumbnail image.
    public func size(_ value: Swift.UInt64) throws {
        try _irandomAccessStream.put_Size(value)
    }

    // MARK: Windows.Storage.Streams.IOutputStream members

    /// Writes data asynchronously in a sequential stream.
    /// - Parameter buffer: The buffer into which the asynchronous writer operation writes.
    /// - Returns: The byte writer operation.
    public func writeAsync(_ buffer: WindowsStorageStreams_IBuffer?) throws -> WindowsFoundation_IAsyncOperationWithProgress<Swift.UInt32, Swift.UInt32> {
        try COM.NullResult.unwrap(_ioutputStream.writeAsync(buffer))
    }

    /// Flushes data asynchronously in a sequential stream.
    /// - Returns: The stream flush operation.
    public func flushAsync() throws -> WindowsFoundation_IAsyncOperation<Swift.Bool> {
        try COM.NullResult.unwrap(_ioutputStream.flushAsync())
    }

    // MARK: Windows.Foundation.IClosable members

    /// Releases system resources that are exposed by a Windows Runtime object.
    public func close() throws {
        try _iclosable.close()
    }

    // MARK: Windows.Storage.Streams.IInputStream members

    /// Returns an asynchronous byte reader object.
    /// - Parameter buffer: The buffer into which the asynchronous read operation places the bytes that are read.
    /// - Parameter count: The number of bytes to read that is less than or equal to the Capacity value.
    /// - Parameter options: Specifies the type of the asynchronous read operation.
    /// - Returns: The asynchronous operation.
    public func readAsync(_ buffer: WindowsStorageStreams_IBuffer?, _ count: Swift.UInt32, _ options: WindowsStorageStreams_InputStreamOptions) throws -> WindowsFoundation_IAsyncOperationWithProgress<WindowsStorageStreams_IBuffer?, Swift.UInt32> {
        try COM.NullResult.unwrap(_iinputStream.readAsync(buffer, count, options))
    }

    /// The original height, in pixels.
    public var originalHeight: Swift.UInt32 {
        get throws {
            try _ithumbnailProperties.get_OriginalHeight()
        }
    }

    /// Gets the original (not scaled) height of the thumbnail image.
    public var originalHeight_: Swift.UInt32 {
        try! self.originalHeight
    }

    /// The original width, in pixels.
    public var originalWidth: Swift.UInt32 {
        get throws {
            try _ithumbnailProperties.get_OriginalWidth()
        }
    }

    /// Gets the original (not scaled) width of the thumbnail image.
    public var originalWidth_: Swift.UInt32 {
        try! self.originalWidth
    }

    /// The value that indicates whether the thumbnail image returned was a cached version with a smaller size.
    public var returnedSmallerCachedSize: Swift.Bool {
        get throws {
            try _ithumbnailProperties.get_ReturnedSmallerCachedSize()
        }
    }

    /// Gets a value that indicates whether the thumbnail image returned was a cached version with a smaller size.
    public var returnedSmallerCachedSize_: Swift.Bool {
        try! self.returnedSmallerCachedSize
    }

    /// The value that indicates if the thumbnail is an icon or an image.
    public var type: WindowsStorageFileProperties_ThumbnailType {
        get throws {
            try _ithumbnailProperties.get_Type()
        }
    }

    /// Gets a value that indicates if the thumbnail is an icon or an image.
    public var type_: WindowsStorageFileProperties_ThumbnailType {
        try! self.type
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsStorageStreams_IRandomAccessStreamWithContentType>) {
        super.init(_wrapping: consume inner)
    }

    private var _lazyIContentTypeProvider: COM.COMReference<SWRT_WindowsStorageStreams_IContentTypeProvider>.Optional = .none

    internal var _icontentTypeProvider: COM.COMInterop<SWRT_WindowsStorageStreams_IContentTypeProvider> {
        get throws {
            try _lazyIContentTypeProvider.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsStorageStreams_IContentTypeProvider.self)).cast()
            }
        }
    }

    private var _lazyIRandomAccessStream: COM.COMReference<SWRT_WindowsStorageStreams_IRandomAccessStream>.Optional = .none

    internal var _irandomAccessStream: COM.COMInterop<SWRT_WindowsStorageStreams_IRandomAccessStream> {
        get throws {
            try _lazyIRandomAccessStream.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsStorageStreams_IRandomAccessStream.self)).cast()
            }
        }
    }

    private var _lazyIOutputStream: COM.COMReference<SWRT_WindowsStorageStreams_IOutputStream>.Optional = .none

    internal var _ioutputStream: COM.COMInterop<SWRT_WindowsStorageStreams_IOutputStream> {
        get throws {
            try _lazyIOutputStream.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsStorageStreams_IOutputStream.self)).cast()
            }
        }
    }

    private var _lazyIClosable: COM.COMReference<SWRT_WindowsFoundation_IClosable>.Optional = .none

    internal var _iclosable: COM.COMInterop<SWRT_WindowsFoundation_IClosable> {
        get throws {
            try _lazyIClosable.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsFoundation_IClosable.self)).cast()
            }
        }
    }

    private var _lazyIInputStream: COM.COMReference<SWRT_WindowsStorageStreams_IInputStream>.Optional = .none

    internal var _iinputStream: COM.COMInterop<SWRT_WindowsStorageStreams_IInputStream> {
        get throws {
            try _lazyIInputStream.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsStorageStreams_IInputStream.self)).cast()
            }
        }
    }

    private var _lazyIThumbnailProperties: COM.COMReference<SWRT_WindowsStorageFileProperties_IThumbnailProperties>.Optional = .none

    internal var _ithumbnailProperties: COM.COMInterop<SWRT_WindowsStorageFileProperties_IThumbnailProperties> {
        get throws {
            try _lazyIThumbnailProperties.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsStorageFileProperties_IThumbnailProperties.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.Storage.FileProperties.StorageItemThumbnail")
            }
        }
    }
}