// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Provides access to the video-related properties of an item (like a file or folder).
public final class WindowsStorageFileProperties_VideoProperties: WindowsRuntime.WinRTImport<WindowsStorageFileProperties_VideoPropertiesBinding>, WindowsStorageFileProperties_IStorageItemExtraPropertiesProtocol {
    /// The video's sum audio and video bitrate.
    public var bitrate: Swift.UInt32 {
        get throws {
            try _interop.get_Bitrate()
        }
    }

    /// Gets the sum audio and video bitrate of the video.
    public var bitrate_: Swift.UInt32 {
        try! self.bitrate
    }

    /// A list of the names of the video's directors.
    public var directors: WindowsFoundationCollections_IVector<Swift.String> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Directors())
        }
    }

    /// Gets the directors of the video.
    public var directors_: WindowsFoundationCollections_IVector<Swift.String>! {
        try! NullResult.catch(self.directors)
    }

    /// The duration.
    public var duration: WindowsFoundation_TimeSpan {
        get throws {
            try _interop.get_Duration()
        }
    }

    /// Gets the duration of the video.
    public var duration_: WindowsFoundation_TimeSpan {
        try! self.duration
    }

    /// The height of the video, in pixels.
    public var height: Swift.UInt32 {
        get throws {
            try _interop.get_Height()
        }
    }

    /// Gets the height of the video.
    public var height_: Swift.UInt32 {
        try! self.height
    }

    /// The collection of keywords.
    public var keywords: WindowsFoundationCollections_IVector<Swift.String> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Keywords())
        }
    }

    /// Gets the collection of keywords associated with the video.
    public var keywords_: WindowsFoundationCollections_IVector<Swift.String>! {
        try! NullResult.catch(self.keywords)
    }

    /// The latitude coordinate where the video was shot.
    public var latitude: Swift.Double? {
        get throws {
            try _interop.get_Latitude()
        }
    }

    /// Gets the latitude coordinate where the video was shot.
    public var latitude_: Swift.Double? {
        try! self.latitude
    }

    /// The longitude coordinate where the photo was taken.
    public var longitude: Swift.Double? {
        get throws {
            try _interop.get_Longitude()
        }
    }

    /// Gets the longitude coordinate where the video was shot.
    public var longitude_: Swift.Double? {
        try! self.longitude
    }

    /// The value that indicates how the video should be rotated to display it correctly.
    public var orientation: WindowsStorageFileProperties_VideoOrientation {
        get throws {
            try _interop.get_Orientation()
        }
    }

    /// Gets a VideoOrientation value that indicates how the video should be rotated to display it correctly.
    public var orientation_: WindowsStorageFileProperties_VideoOrientation {
        try! self.orientation
    }

    /// A list of the names of the video's producers.
    public var producers: WindowsFoundationCollections_IVector<Swift.String> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Producers())
        }
    }

    /// Gets the producers of the video.
    public var producers_: WindowsFoundationCollections_IVector<Swift.String>! {
        try! NullResult.catch(self.producers)
    }

    /// The name of the video's publisher.
    public var publisher: Swift.String {
        get throws {
            try _interop.get_Publisher()
        }
    }

    /// Sets the publisher of the video.
    /// - Parameter newValue: The name of the video's publisher.
    public func publisher(_ value: Swift.String) throws {
        try _interop.put_Publisher(value)
    }

    /// Gets or sets the publisher of the video.
    public var publisher_: Swift.String {
        get {
            try! self.publisher
        }
        set {
            try! self.publisher(newValue)
        }
    }

    /// The media file rating, as a value between 0 and 99.
    public var rating: Swift.UInt32 {
        get throws {
            try _interop.get_Rating()
        }
    }

    /// Sets the rating associated with a video file.
    /// - Parameter newValue: The media file rating, as a value between 0 and 99.
    public func rating(_ value: Swift.UInt32) throws {
        try _interop.put_Rating(value)
    }

    /// Gets or sets the rating associated with a video file.
    public var rating_: Swift.UInt32 {
        get {
            try! self.rating
        }
        set {
            try! self.rating(newValue)
        }
    }

    /// The video's subtitle.
    public var subtitle: Swift.String {
        get throws {
            try _interop.get_Subtitle()
        }
    }

    /// Sets the subtitle of the video.
    /// - Parameter newValue: The video's subtitle.
    public func subtitle(_ value: Swift.String) throws {
        try _interop.put_Subtitle(value)
    }

    /// Gets or sets the subtitle of the video.
    public var subtitle_: Swift.String {
        get {
            try! self.subtitle
        }
        set {
            try! self.subtitle(newValue)
        }
    }

    /// The video's title.
    public var title: Swift.String {
        get throws {
            try _interop.get_Title()
        }
    }

    /// Sets the title of the video.
    /// - Parameter newValue: The video's title.
    public func title(_ value: Swift.String) throws {
        try _interop.put_Title(value)
    }

    /// Gets or sets the title of the video.
    public var title_: Swift.String {
        get {
            try! self.title
        }
        set {
            try! self.title(newValue)
        }
    }

    /// The width of the video, in pixels.
    public var width: Swift.UInt32 {
        get throws {
            try _interop.get_Width()
        }
    }

    /// Gets the width of the video.
    public var width_: Swift.UInt32 {
        try! self.width
    }

    /// A list of the names of the video's script writers.
    public var writers: WindowsFoundationCollections_IVector<Swift.String> {
        get throws {
            try COM.NullResult.unwrap(_interop.get_Writers())
        }
    }

    /// Gets the script writers for the video.
    public var writers_: WindowsFoundationCollections_IVector<Swift.String>! {
        try! NullResult.catch(self.writers)
    }

    /// The video's release year.
    public var year: Swift.UInt32 {
        get throws {
            try _interop.get_Year()
        }
    }

    /// Sets the year that the video was shot or released.
    /// - Parameter newValue: The video's release year.
    public func year(_ value: Swift.UInt32) throws {
        try _interop.put_Year(value)
    }

    /// Gets or sets the year that the video was shot or released.
    public var year_: Swift.UInt32 {
        get {
            try! self.year
        }
        set {
            try! self.year(newValue)
        }
    }

    // MARK: Windows.Storage.FileProperties.IStorageItemExtraProperties members

    public func retrievePropertiesAsync(_ propertiesToRetrieve: WindowsFoundationCollections_IIterable<Swift.String>?) throws -> WindowsFoundation_IAsyncOperation<WindowsFoundationCollections_IMap<Swift.String, WindowsRuntime.IInspectable?>?> {
        try COM.NullResult.unwrap(_istorageItemExtraProperties.retrievePropertiesAsync(propertiesToRetrieve))
    }

    public func savePropertiesAsync(_ propertiesToSave: WindowsFoundationCollections_IIterable<WindowsFoundationCollections_IKeyValuePair<Swift.String, WindowsRuntime.IInspectable?>?>?) throws -> WindowsFoundation_IAsyncAction {
        try COM.NullResult.unwrap(_istorageItemExtraProperties.savePropertiesAsync(propertiesToSave))
    }

    /// Saves all properties associated with the item.
    /// - Returns: No object or value is returned when this method completes.
    public func savePropertiesAsync() throws -> WindowsFoundation_IAsyncAction {
        try COM.NullResult.unwrap(_istorageItemExtraProperties.savePropertiesAsyncOverloadDefault())
    }

    // MARK: Implementation details

    public required init(_wrapping inner: consuming COM.COMReference<SWRT_WindowsStorageFileProperties_IVideoProperties>) {
        super.init(_wrapping: consume inner)
    }

    private var _lazyIStorageItemExtraProperties: COM.COMReference<SWRT_WindowsStorageFileProperties_IStorageItemExtraProperties>.Optional = .none

    internal var _istorageItemExtraProperties: COM.COMInterop<SWRT_WindowsStorageFileProperties_IStorageItemExtraProperties> {
        get throws {
            try _lazyIStorageItemExtraProperties.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_WindowsStorageFileProperties_IStorageItemExtraProperties.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.Storage.FileProperties.VideoProperties")
            }
        }
    }
}