// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Saves and retrieves the properties of a storage item.
public typealias WindowsStorageFileProperties_IStorageItemExtraProperties = any WindowsStorageFileProperties_IStorageItemExtraPropertiesProtocol


/// Saves and retrieves the properties of a storage item.
public protocol WindowsStorageFileProperties_IStorageItemExtraPropertiesProtocol: IInspectableProtocol {
    func retrievePropertiesAsync(_ propertiesToRetrieve: WindowsFoundationCollections_IIterable<Swift.String>?) throws -> WindowsFoundation_IAsyncOperation<WindowsFoundationCollections_IMap<Swift.String, WindowsRuntime.IInspectable?>?>
    func savePropertiesAsync(_ propertiesToSave: WindowsFoundationCollections_IIterable<WindowsFoundationCollections_IKeyValuePair<Swift.String, WindowsRuntime.IInspectable?>?>?) throws -> WindowsFoundation_IAsyncAction

    /// Saves all properties associated with the item.
    /// - Returns: An object for managing the asynchronous save operation.
    func savePropertiesAsync() throws -> WindowsFoundation_IAsyncAction
}