// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Indicates a system-defined group of file properties.
public struct WindowsStorageFileProperties_PropertyPrefetchOptions: CStyleEnum {
    public var rawValue: Swift.UInt32

    public init(rawValue: Swift.UInt32 = 0) {
        self.rawValue = rawValue
    }

    /// No specific, system-defined property group.
    public static let none = Self()

    /// A group of music-related properties that can be access through a MusicProperties object.
    public static let musicProperties = Self(rawValue: 1)

    /// A group of video-related properties that can be access through a VideoProperties object.
    public static let videoProperties = Self(rawValue: 2)

    /// A group of image-related properties that can be access through a ImageProperties object.
    public static let imageProperties = Self(rawValue: 4)

    /// A group of document-related properties that can be access through a DocumentProperties object.
    public static let documentProperties = Self(rawValue: 8)

    /// A group of basic properties that can be access through a BasicProperties object.
    public static let basicProperties = Self(rawValue: 16)
}

// MARK: OptionSet and bitwise operators

extension WindowsStorageFileProperties_PropertyPrefetchOptions: OptionSet {
    public static prefix func ~(value: Self) -> Self {
        Self(rawValue: ~value.rawValue)
    }

    public static func |(lhs: Self, rhs: Self) -> Self {
        Self(rawValue: lhs.rawValue | rhs.rawValue)
    }

    public static func |=(lhs: inout Self, rhs: Self) {
        lhs = Self(rawValue: lhs.rawValue | rhs.rawValue)
    }

    public static func &(lhs: Self, rhs: Self) -> Self {
        Self(rawValue: lhs.rawValue & rhs.rawValue)
    }

    public static func &=(lhs: inout Self, rhs: Self) {
        lhs = Self(rawValue: lhs.rawValue & rhs.rawValue)
    }

    public static func ^(lhs: Self, rhs: Self) -> Self {
        Self(rawValue: lhs.rawValue ^ rhs.rawValue)
    }

    public static func ^=(lhs: inout Self, rhs: Self) {
        lhs = Self(rawValue: lhs.rawValue ^ rhs.rawValue)
    }
}