// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP


/// Represents a shape that clips a portion of a visual. The visible portion of the visual is a shape defined by a CompositionGeometry. The portion of the visual outside the geometry is clipped.
public final class MicrosoftUIComposition_CompositionGeometricClip: MicrosoftUIComposition_CompositionClip, @unchecked Sendable {
    /// A CompositionGeometry that defines the shape of the clip. The default is null.
    public var geometry: MicrosoftUIComposition_CompositionGeometry {
        get throws {
            try COM.NullResult.unwrap(_icompositionGeometricClip.get_Geometry())
        }
    }

    /// Sets CompositionGeometry that defines the shape of the clip.
    /// - Parameter newValue: A CompositionGeometry that defines the shape of the clip. The default is null.
    public func geometry(_ value: MicrosoftUIComposition_CompositionGeometry?) throws {
        try _icompositionGeometricClip.put_Geometry(value)
    }

    /// Gets or sets CompositionGeometry that defines the shape of the clip.
    public var geometry_: MicrosoftUIComposition_CompositionGeometry! {
        get {
            try! NullResult.catch(self.geometry)
        }
        set {
            try! self.geometry(newValue)
        }
    }

    /// A CompositionViewBox that maps the shape visual tree coordinates onto the visual.
    public var viewBox: MicrosoftUIComposition_CompositionViewBox {
        get throws {
            try COM.NullResult.unwrap(_icompositionGeometricClip.get_ViewBox())
        }
    }

    /// Sets a CompositionViewBox that maps the shape visual tree coordinates onto the visual.
    /// - Parameter newValue: A CompositionViewBox that maps the shape visual tree coordinates onto the visual.
    public func viewBox(_ value: MicrosoftUIComposition_CompositionViewBox?) throws {
        try _icompositionGeometricClip.put_ViewBox(value)
    }

    /// Gets or sets a CompositionViewBox that maps the shape visual tree coordinates onto the visual.
    public var viewBox_: MicrosoftUIComposition_CompositionViewBox! {
        get {
            try! NullResult.catch(self.viewBox)
        }
        set {
            try! self.viewBox(newValue)
        }
    }

    // MARK: Implementation details

    public init(_wrapping inner: consuming COM.COMReference<SWRT_MicrosoftUIComposition_ICompositionGeometricClip>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    private var _lazyICompositionGeometricClip: COM.COMReference<SWRT_MicrosoftUIComposition_ICompositionGeometricClip>.Optional = .none

    internal var _icompositionGeometricClip: COM.COMInterop<SWRT_MicrosoftUIComposition_ICompositionGeometricClip> {
        get throws {
            try _lazyICompositionGeometricClip.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_MicrosoftUIComposition_ICompositionGeometricClip.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Microsoft.UI.Composition.CompositionGeometricClip")
            }
        }
    }
}