// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP


/// Represents a linear function for interpolating between animation key frames.
public final class MicrosoftUIComposition_LinearEasingFunction: MicrosoftUIComposition_CompositionEasingFunction, @unchecked Sendable {
    // MARK: Implementation details

    public init(_wrapping inner: consuming COM.COMReference<SWRT_MicrosoftUIComposition_ILinearEasingFunction>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    private var _lazyILinearEasingFunction: COM.COMReference<SWRT_MicrosoftUIComposition_ILinearEasingFunction>.Optional = .none

    internal var _ilinearEasingFunction: COM.COMInterop<SWRT_MicrosoftUIComposition_ILinearEasingFunction> {
        get throws {
            try _lazyILinearEasingFunction.lazyInitInterop {
                try _queryInterface(uuidof(SWRT_MicrosoftUIComposition_ILinearEasingFunction.self)).cast()
            }
        }
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Microsoft.UI.Composition.LinearEasingFunction")
            }
        }
    }
}