// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

extension WindowsGraphicsDirectXDirect3D11_Direct3DSurfaceDescription: WindowsRuntime.StructBinding, COM.PODBinding {
    public typealias SwiftValue = Self
    public typealias ABIValue = SWRT_WindowsGraphicsDirectXDirect3D11_Direct3DSurfaceDescription

    public static let typeName = "Windows.Graphics.DirectX.Direct3D11.Direct3DSurfaceDescription"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0xE7B42E32, 0xF3E4, 0x5BC6, 0xA7F8, 0x8EA0DCA7450F)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xE0DAF86D, 0x1F4F, 0x5819, 0x9C0A, 0xE58A0424A02F)
    }

    public static var abiDefaultValue: SWRT_WindowsGraphicsDirectXDirect3D11_Direct3DSurfaceDescription {
        .init()
    }

    public static func fromABI(_ value: SWRT_WindowsGraphicsDirectXDirect3D11_Direct3DSurfaceDescription) -> Self {
        .init(
            width: value.Width,
            height: value.Height,
            format: WindowsGraphicsDirectX_DirectXPixelFormat.fromABI(value.Format),
            multisampleDescription: WindowsGraphicsDirectXDirect3D11_Direct3DMultisampleDescription.fromABI(value.MultisampleDescription)
        )
    }

    public static func toABI(_ value: Self) -> SWRT_WindowsGraphicsDirectXDirect3D11_Direct3DSurfaceDescription {
        .init(
            Width: value.width,
            Height: value.height,
            Format: WindowsGraphicsDirectX_DirectXPixelFormat.toABI(value.format),
            MultisampleDescription: WindowsGraphicsDirectXDirect3D11_Direct3DMultisampleDescription.toABI(value.multisampleDescription)
        )
    }
}