// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI


/// Possible results when access to protected content is requested or queried.
public struct WindowsSecurityEnterpriseData_ProtectionPolicyEvaluationResult: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Access is allowed.
    public static let allowed = Self()

    /// Access is blocked.
    public static let blocked = Self(rawValue: 1)

    /// Consent is required for access.
    public static let consentRequired = Self(rawValue: 2)
}