// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// A delegate that handles share providers.
/// - Parameter operation: # Windows.ApplicationModel.DataTransfer.ShareProviderHandler
public typealias WindowsApplicationModelDataTransfer_ShareProviderHandler = (WindowsApplicationModelDataTransfer_ShareProviderOperation?) throws -> Swift.Void