// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK

/// Represents the method that will handle the UnhandledException event.
/// - Parameter sender: The object where the handler is attached.
/// - Parameter e: Event data.
public typealias MicrosoftUIXaml_UnhandledExceptionEventHandler = (WindowsRuntime.IInspectable?, MicrosoftUIXaml_UnhandledExceptionEventArgs?) throws -> Swift.Void