// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinUI_ABI
import UWP
import WindowsAppSDK


/// Defines constants that specify a control's preference for whether sounds are played.
public struct MicrosoftUIXaml_ElementSoundMode: CStyleEnum {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// Sound is played based on the ElementSoundPlayer.State setting.
    public static let `default` = Self()

    /// Sound is played only when focus on the control changes.
    public static let focusOnly = Self(rawValue: 1)

    /// No sounds are played.
    public static let off = Self(rawValue: 2)
}