// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Represents an asynchronous operation that can report progress updates to callers. This is the return type for many Windows Runtime asynchronous methods that have results and also report progress.
public typealias WindowsFoundation_IAsyncOperationWithProgress<TResult, TProgress> = any WindowsFoundation_IAsyncOperationWithProgressProtocol<TResult, TProgress>


/// Represents an asynchronous operation that can report progress updates to callers. This is the return type for many Windows Runtime asynchronous methods that have results and also report progress.
public protocol WindowsFoundation_IAsyncOperationWithProgressProtocol<TResult, TProgress>: WindowsFoundation_IAsyncInfoProtocol {
    associatedtype TResult
    associatedtype TProgress

    /// Returns the results of the operation.
    /// - Returns: The results of the operation.
    func getResults() throws -> TResult

    /// A reference to the callback method that handles progress notifications. Implement the AsyncOperationProgressHandler<TResult, TProgress> delegate to define your callback. *TProgress* defines the progress unit type, which varies by method implementation.
    var progress: WindowsFoundation_AsyncOperationProgressHandler<TResult, TProgress> { get throws }

    /// Sets the method that handles progress notifications.
    /// - Parameter newValue: A reference to the callback method that handles progress notifications. Implement the AsyncOperationProgressHandler<TResult, TProgress> delegate to define your callback. *TProgress* defines the progress unit type, which varies by method implementation.
    func progress(_ handler: WindowsFoundation_AsyncOperationProgressHandler<TResult, TProgress>?) throws

    /// The method that handles the notification.
    var completed: WindowsFoundation_AsyncOperationWithProgressCompletedHandler<TResult, TProgress> { get throws }

    /// Sets the method that handles the operation completed notification.
    /// - Parameter newValue: The method that handles the notification.
    func completed(_ handler: WindowsFoundation_AsyncOperationWithProgressCompletedHandler<TResult, TProgress>?) throws
}

extension WindowsFoundation_IAsyncOperationWithProgressProtocol {
    /// Gets or sets the method that handles progress notifications.
    public var progress_: WindowsFoundation_AsyncOperationProgressHandler<TResult, TProgress>! {
        get {
            try! NullResult.catch(self.progress)
        }
        set {
            try! self.progress(newValue)
        }
    }

    /// Gets or sets the method that handles the operation completed notification.
    public var completed_: WindowsFoundation_AsyncOperationWithProgressCompletedHandler<TResult, TProgress>! {
        get {
            try! NullResult.catch(self.completed)
        }
        set {
            try! self.completed(newValue)
        }
    }
}