// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WindowsAppSDK_ABI
import UWP

public class MicrosoftUIDispatching_DispatcherQueueShutdownStartingEventArgsBinding: WindowsRuntime.RuntimeClassBinding {
    public typealias SwiftObject = MicrosoftUIDispatching_DispatcherQueueShutdownStartingEventArgs
    public typealias ABIStruct = SWRT_MicrosoftUIDispatching_IDispatcherQueueShutdownStartingEventArgs

    public static let typeName = "Microsoft.UI.Dispatching.DispatcherQueueShutdownStartingEventArgs"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MicrosoftUIDispatching_DispatcherQueueShutdownStartingEventArgs(_wrapping: consume reference)
    }
}