// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public enum WindowsStorageStreams_IContentTypeProviderBinding: WindowsRuntime.InterfaceBinding {
    public typealias SwiftObject = WindowsStorageStreams_IContentTypeProvider
    public typealias ABIStruct = SWRT_WindowsStorageStreams_IContentTypeProvider

    public static let typeName = "Windows.Storage.Streams.IContentTypeProvider"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        Import(_wrapping: consume reference)
    }

    private final class Import: WinRTImport<WindowsStorageStreams_IContentTypeProviderBinding>, WindowsStorageStreams_IContentTypeProviderProtocol {
        public var contentType: Swift.String {
            get throws {
                try _interop.get_ContentType()
            }
        }
    }

    public static var virtualTablePointer: UnsafeRawPointer {
        .init(withUnsafePointer(to: &virtualTable) { $0 })
    }

    private static var virtualTable = SWRT_WindowsStorageStreams_IContentTypeProvider_VirtualTable(
        QueryInterface: { IUnknownVirtualTable.QueryInterface($0, $1, $2) },
        AddRef: { IUnknownVirtualTable.AddRef($0) },
        Release: { IUnknownVirtualTable.Release($0) },
        GetIids: { IInspectableVirtualTable.GetIids($0, $1, $2) },
        GetRuntimeClassName: { IInspectableVirtualTable.GetRuntimeClassName($0, $1) },
        GetTrustLevel: { IInspectableVirtualTable.GetTrustLevel($0, $1) },
        get_ContentType: { this, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let _result_swift = try this.contentType
            _result.pointee = try WindowsRuntime.StringBinding.toABI(_result_swift)
        } }
    )
}